const pictogramData = [
    // Core: Personas y Pronombres
    { id: 'yo', category: 'Personas', variations: [{ text: 'Yo', icon: 'mdi:account' }] },
    { id: 'tu', category: 'Personas', variations: [{ text: 'Tú', icon: 'mdi:account-outline' }] },
    { id: 'el', category: 'Personas', variations: [{ text: 'Él', icon: 'mdi:gender-male' }] },
    { id: 'ella', category: 'Personas', variations: [{ text: 'Ella', icon: 'mdi:gender-female' }] },
    { id: 'nosotros', category: 'Personas', variations: [{ text: 'Nosotros', icon: 'mdi:account-group' }] },
    { id: 'ellos', category: 'Personas', variations: [{ text: 'Ellos', icon: 'mdi:account-multiple' }] },
    { id: 'mama', category: 'Personas', variations: [{ text: 'Mamá', icon: 'mdi:human-female-boy' }] },
    { id: 'papa', category: 'Personas', variations: [{ text: 'Papá', icon: 'mdi:human-male-girl' }] },
    { id: 'bebe', category: 'Personas', variations: [{ text: 'Bebé', icon: 'mdi:baby-carriage' }] },
    { id: 'nino', category: 'Personas', variations: [{ text: 'Niño', icon: 'mdi:human-child' }, { text: 'Niños', icon: 'mdi:human-male-male' }] },
    { id: 'nina', category: 'Personas', variations: [{ text: 'Niña', icon: 'mdi:human-female-girl' }, { text: 'Niñas', icon: 'mdi:human-female-female' }] },
    { id: 'amigo', category: 'Personas', variations: [{ text: 'Amigo', icon: 'mdi:account-heart' }, { text: 'Amigos', icon: 'mdi:account-heart-outline' }] },
    { id: 'doctor', category: 'Personas', variations: [{ text: 'Doctor', icon: 'mdi:doctor' }] },
    { id: 'profesor', category: 'Personas', variations: [{ text: 'Profesor', icon: 'mdi:teach' }] },

    // Core: Verbos / Acciones
    { id: 'quiero', category: 'Acciones', variations: [{ text: 'Quiero', icon: 'mdi:hand-pointing-right' }] },
    { id: 'no_quiero', category: 'Acciones', variations: [{ text: 'No quiero', icon: 'mdi:hand-saw' }] },
    { id: 'comer', category: 'Acciones', variations: [{ text: 'Comer', icon: 'mdi:food-apple' }, { text: 'Comiendo', icon: 'mdi:food-apple-outline' }, { text: 'Comí', icon: 'mdi:food-apple' }] },
    { id: 'beber', category: 'Acciones', variations: [{ text: 'Beber', icon: 'mdi:cup-water' }, { text: 'Bebiendo', icon: 'mdi:cup' }, { text: 'Bebí', icon: 'mdi:cup-off' }] },
    { id: 'jugar', category: 'Acciones', variations: [{ text: 'Jugar', icon: 'mdi:gamepad-variant' }, { text: 'Jugando', icon: 'mdi:gamepad' }, { text: 'Jugué', icon: 'mdi:gamepad-outline' }] },
    { id: 'ir', category: 'Acciones', variations: [{ text: 'Ir', icon: 'mdi:arrow-right-bold-circle' }, { text: 'Voy', icon: 'mdi:arrow-right-bold-circle-outline' }, { text: 'Fui', icon: 'mdi:arrow-right-bold' }] },
    { id: 'venir', category: 'Acciones', variations: [{ text: 'Venir', icon: 'mdi:arrow-left-bold-circle' }, { text: 'Vengo', icon: 'mdi:arrow-left-bold-circle-outline' }, { text: 'Vine', icon: 'mdi:arrow-left-bold' }] },
    { id: 'dormir', category: 'Acciones', variations: [{ text: 'Dormir', icon: 'mdi:sleep' }, { text: 'Durmiendo', icon: 'mdi:sleep-off' }, { text: 'Dormí', icon: 'mdi:bed' }] },
    { id: 'despertar', category: 'Acciones', variations: [{ text: 'Despertar', icon: 'mdi:weather-sunny' }, { text: 'Despertando', icon: 'mdi:weather-sunny-alert' }, { text: 'Desperté', icon: 'mdi:weather-sunny-off' }] },
    { id: 'mirar', category: 'Acciones', variations: [{ text: 'Mirar', icon: 'mdi:eye' }, { text: 'Mirando', icon: 'mdi:eye-outline' }, { text: 'Miré', icon: 'mdi:eye-off' }] },
    { id: 'escuchar', category: 'Acciones', variations: [{ text: 'Escuchar', icon: 'mdi:ear-hearing' }, { text: 'Escuchando', icon: 'mdi:ear-hearing-loop' }, { text: 'Escuché', icon: 'mdi:ear-hearing-off' }] },
    { id: 'hablar', category: 'Acciones', variations: [{ text: 'Hablar', icon: 'mdi:message-text' }, { text: 'Hablando', icon: 'mdi:message-text-outline' }, { text: 'Hablé', icon: 'mdi:message' }] },
    { id: 'cantar', category: 'Acciones', variations: [{ text: 'Cantar', icon: 'mdi:microphone-variant' }, { text: 'Cantando', icon: 'mdi:microphone' }, { text: 'Canté', icon: 'mdi:microphone-off' }] },
    { id: 'bailar', category: 'Acciones', variations: [{ text: 'Bailar', icon: 'mdi:dance-ballroom' }, { text: 'Bailando', icon: 'mdi:human-female-dance' }, { text: 'Bailé', icon: 'mdi:human-male-dance' }] },
    { id: 'leer', category: 'Acciones', variations: [{ text: 'Leer', icon: 'mdi:book-open-page-variant' }, { text: 'Leyendo', icon: 'mdi:book-open' }, { text: 'Leí', icon: 'mdi:book' }] },
    { id: 'escribir', category: 'Acciones', variations: [{ text: 'Escribir', icon: 'mdi:pencil' }, { text: 'Escribiendo', icon: 'mdi:pencil-outline' }, { text: 'Escribí', icon: 'mdi:pencil-off' }] },
    { id: 'pintar', category: 'Acciones', variations: [{ text: 'Pintar', icon: 'mdi:palette' }, { text: 'Pintando', icon: 'mdi:palette-outline' }, { text: 'Pinté', icon: 'mdi:palette-swatch' }] },
    { id: 'correr', category: 'Acciones', variations: [{ text: 'Correr', icon: 'mdi:run' }, { text: 'Corriendo', icon: 'mdi:run-fast' }, { text: 'Corrí', icon: 'mdi:walk' }] },
    { id: 'caminar', category: 'Acciones', variations: [{ text: 'Caminar', icon: 'mdi:walk' }, { text: 'Caminando', icon: 'mdi:human-male-female' }, { text: 'Caminé', icon: 'mdi:foot-print' }] },
    { id: 'saltar', category: 'Acciones', variations: [{ text: 'Saltar', icon: 'mdi:jump-rope' }, { text: 'Saltando', icon: 'mdi:rabbit' }, { text: 'Salté', icon: 'mdi:human-jump' }] },
    { id: 'sentarse', category: 'Acciones', variations: [{ text: 'Sentarse', icon: 'mdi:seat' }, { text: 'Sentado', icon: 'mdi:seat-outline' }, { text: 'Me senté', icon: 'mdi:seat-recline' }] },
    { id: 'levantarse', category: 'Acciones', variations: [{ text: 'Levantarse', icon: 'mdi:human-male-height' }, { text: 'Levantado', icon: 'mdi:human-male-height-variant' }, { text: 'Me levanté', icon: 'mdi:human-handsup' }] },
    { id: 'abrir', category: 'Acciones', variations: [{ text: 'Abrir', icon: 'mdi:door-open' }, { text: 'Abriendo', icon: 'mdi:door' }, { text: 'Abrí', icon: 'mdi:door-sliding' }] },
    { id: 'cerrar', category: 'Acciones', variations: [{ text: 'Cerrar', icon: 'mdi:door-closed' }, { text: 'Cerrando', icon: 'mdi:door-closed-lock' }, { text: 'Cerré', icon: 'mdi:door-sliding-lock' }] },
    { id: 'dar', category: 'Acciones', variations: [{ text: 'Dar', icon: 'mdi:gift' }, { text: 'Dando', icon: 'mdi:gift-outline' }, { text: 'Di', icon: 'mdi:gift-open' }] },
    { id: 'recibir', category: 'Acciones', variations: [{ text: 'Recibir', icon: 'mdi:download' }, { text: 'Recibiendo', icon: 'mdi:download-outline' }, { text: 'Recibí', icon: 'mdi:download-off' }] },
    { id: 'ayudar', category: 'Acciones', variations: [{ text: 'Ayudar', icon: 'mdi:help-circle' }, { text: 'Ayudando', icon: 'mdi:help-circle-outline' }, { text: 'Ayudé', icon: 'mdi:help' }] },
    { id: 'trabajar', category: 'Acciones', variations: [{ text: 'Trabajar', icon: 'mdi:briefcase' }, { text: 'Trabajando', icon: 'mdi:briefcase-outline' }, { text: 'Trabajé', icon: 'mdi:briefcase-off' }] },
    { id: 'estudiar', category: 'Acciones', variations: [{ text: 'Estudiar', icon: 'mdi:school' }, { text: 'Estudiando', icon: 'mdi:school-outline' }, { text: 'Estudié', icon: 'mdi:book-open-variant' }] },
    { id: 'lavar', category: 'Acciones', variations: [{ text: 'Lavar', icon: 'mdi:water' }, { text: 'Lavando', icon: 'mdi:water-outline' }, { text: 'Lavé', icon: 'mdi:water-off' }] },
    { id: 'banarse', category: 'Acciones', variations: [{ text: 'Bañarse', icon: 'mdi:shower-head' }, { text: 'Bañando', icon: 'mdi:shower' }, { text: 'Me bañé', icon: 'mdi:hot-tub' }] },
    { id: 'vestirse', category: 'Acciones', variations: [{ text: 'Vestirse', icon: 'mdi:tshirt-crew' }, { text: 'Vistiendo', icon: 'mdi:tshirt-crew-outline' }, { text: 'Me vestí', icon: 'mdi:human-female-dress' }] },
    { id: 'peinarse', category: 'Acciones', variations: [{ text: 'Peinarse', icon: 'mdi:hair-dryer' }, { text: 'Peinando', icon: 'mdi:hair-dryer-outline' }, { text: 'Me peiné', icon: 'mdi:face-woman-shimmer' }] },
    { id: 'cepillarse', category: 'Acciones', variations: [{ text: 'Cepillarse', icon: 'mdi:brush' }, { text: 'Cepillando', icon: 'mdi:brush-outline' }, { text: 'Me cepillé', icon: 'mdi:tooth' }] },

    // Core: Preguntas
    { id: 'que', category: 'Preguntas', variations: [{ text: 'Qué', icon: 'mdi:help-box' }] },
    { id: 'quien', category: 'Preguntas', variations: [{ text: 'Quién', icon: 'mdi:account-question' }] },
    { id: 'cuando', category: 'Preguntas', variations: [{ text: 'Cuándo', icon: 'mdi:calendar-question' }] },
    { id: 'donde', category: 'Preguntas', variations: [{ text: 'Dónde', icon: 'mdi:map-marker-question' }] },
    { id: 'porque', category: 'Preguntas', variations: [{ text: 'Porqué', icon: 'mdi:comment-question' }] },
    { id: 'como', category: 'Preguntas', variations: [{ text: 'Cómo', icon: 'mdi:information' }] },

    // Core: Pequeñas Palabras
    { id: 'y', category: 'Pequeñas Palabras', variations: [{ text: 'Y', icon: 'mdi:plus' }] },
    { id: 'con', category: 'Pequeñas Palabras', variations: [{ text: 'Con', icon: 'mdi:link' }] },
    { id: 'el', category: 'Pequeñas Palabras', variations: [{ text: 'El', icon: 'mdi:alpha-e-box' }] },
    { id: 'la', category: 'Pequeñas Palabras', variations: [{ text: 'La', icon: 'mdi:alpha-l-box' }] },
    { id: 'en', category: 'Pequeñas Palabras', variations: [{ text: 'En', icon: 'mdi:alpha-e-box-outline' }] },
    { id: 'pero', category: 'Pequeñas Palabras', variations: [{ text: 'Pero', icon: 'mdi:alpha-p-box' }] },

    // Fringe: Comida
    { id: 'agua', category: 'Comida', variations: [{ text: 'Agua', icon: 'mdi:cup' }] },
    { id: 'leche', category: 'Comida', variations: [{ text: 'Leche', icon: 'mdi:cup-off' }] },
    { id: 'jugo', category: 'Comida', variations: [{ text: 'Jugo', icon: 'mdi:food-fork-drink' }] },
    { id: 'pan', category: 'Comida', variations: [{ text: 'Pan', icon: 'mdi:bread-slice' }] },
    { id: 'manzana', category: 'Comida', variations: [{ text: 'Manzana', icon: 'mdi:food-apple-outline' }, { text: 'Manzanas', icon: 'mdi:food-apple' }] },
    { id: 'platano', category: 'Comida', variations: [{ text: 'Plátano', icon: 'mdi:food-banana' }] },
    { id: 'naranja', category: 'Comida', variations: [{ text: 'Naranja', icon: 'mdi:food-orange' }] },
    { id: 'fresa', category: 'Comida', variations: [{ text: 'Fresa', icon: 'mdi:food-strawberry' }] },
    { id: 'galleta', category: 'Comida', variations: [{ text: 'Galleta', icon: 'mdi:cookie' }, { text: 'Galletas', icon: 'mdi:cookie-outline' }] },
    { id: 'queso', category: 'Comida', variations: [{ text: 'Queso', icon: 'mdi:cheese' }] },
    { id: 'huevo', category: 'Comida', variations: [{ text: 'Huevo', icon: 'mdi:egg-easter' }, { text: 'Huevos', icon: 'mdi:egg' }] },
    { id: 'pollo', category: 'Comida', variations: [{ text: 'Pollo', icon: 'mdi:food-drumstick' }] },
    { id: 'carne', category: 'Comida', variations: [{ text: 'Carne', icon: 'mdi:food-steak' }] },
    { id: 'pescado', category: 'Comida', variations: [{ text: 'Pescado', icon: 'mdi:fish' }] },
    { id: 'arroz', category: 'Comida', variations: [{ text: 'Arroz', icon: 'mdi:rice' }] },
    { id: 'pasta', category: 'Comida', variations: [{ text: 'Pasta', icon: 'mdi:food-croissant' }] },
    { id: 'sopa', category: 'Comida', variations: [{ text: 'Sopa', icon: 'mdi:bowl-mix' }] },
    { id: 'ensalada', category: 'Comida', variations: [{ text: 'Ensalada', icon: 'mdi:leaf' }] },
    { id: 'helado', category: 'Comida', variations: [{ text: 'Helado', icon: 'mdi:ice-cream' }] },
    { id: 'torta', category: 'Comida', variations: [{ text: 'Torta', icon: 'mdi:cake-variant' }] },
    { id: 'desayuno', category: 'Comida', variations: [{ text: 'Desayuno', icon: 'mdi:weather-sunset-up' }] },
    { id: 'almuerzo', category: 'Comida', variations: [{ text: 'Almuerzo', icon: 'mdi:weather-sunny' }] },
    { id: 'cena', category: 'Comida', variations: [{ text: 'Cena', icon: 'mdi:weather-night' }] },

    // Fringe: Ropa
    { id: 'camiseta', category: 'Ropa', variations: [{ text: 'Camiseta', icon: 'mdi:tshirt-v' }] },
    { id: 'pantalon', category: 'Ropa', variations: [{ text: 'Pantalón', icon: 'mdi:pants' }] },
    { id: 'vestido', category: 'Ropa', variations: [{ text: 'Vestido', icon: 'mdi:human-female-dress' }] },
    { id: 'falda', category: 'Ropa', variations: [{ text: 'Falda', icon: 'mdi:skirt' }] },
    { id: 'zapatos', category: 'Ropa', variations: [{ text: 'Zapatos', icon: 'mdi:shoe-sneaker' }] },
    { id: 'medias', category: 'Ropa', variations: [{ text: 'Medias', icon: 'mdi:socks' }] },
    { id: 'abrigo', category: 'Ropa', variations: [{ text: 'Abrigo', icon: 'mdi:jacket' }] },
    { id: 'sombrero', category: 'Ropa', variations: [{ text: 'Sombrero', icon: 'mdi:hat-fedora' }] },
    { id: 'gafas', category: 'Ropa', variations: [{ text: 'Gafas', icon: 'mdi:glasses' }] },

    // Fringe: Animales
    { id: 'perro', category: 'Animales', variations: [{ text: 'Perro', icon: 'mdi:dog' }, { text: 'Perros', icon: 'mdi:dog-side' }] },
    { id: 'gato', category: 'Animales', variations: [{ text: 'Gato', icon: 'mdi:cat' }, { text: 'Gatos', icon: 'mdi:cat-off' }] },
    { id: 'pajaro', category: 'Animales', variations: [{ text: 'Pájaro', icon: 'mdi:bird' }] },
    { id: 'pez', category: 'Animales', variations: [{ text: 'Pez', icon: 'mdi:fish' }, { text: 'Peces', icon: 'mdi:fish-off' }] },
    { id: 'conejo', category: 'Animales', variations: [{ text: 'Conejo', icon: 'mdi:rabbit' }] },
    { id: 'caballo', category: 'Animales', variations: [{ text: 'Caballo', icon: 'mdi:horse' }] },
    { id: 'vaca', category: 'Animales', variations: [{ text: 'Vaca', icon: 'mdi:cow' }] },
    { id: 'cerdo', category: 'Animales', variations: [{ text: 'Cerdo', icon: 'mdi:pig' }] },
    { id: 'oveja', category: 'Animales', variations: [{ text: 'Oveja', icon: 'mdi:sheep' }] },
    { id: 'leon', category: 'Animales', variations: [{ text: 'León', icon: 'mdi:lion' }] },
    { id: 'tigre', category: 'Animales', variations: [{ text: 'Tigre', icon: 'mdi:tiger' }] },
    { id: 'elefante', category: 'Animales', variations: [{ text: 'Elefante', icon: 'mdi:elephant' }] },
    { id: 'mono', category: 'Animales', variations: [{ text: 'Mono', icon: 'mdi:monkey' }] },
    { id: 'serpiente', category: 'Animales', variations: [{ text: 'Serpiente', icon: 'mdi:snake' }] },
    { id: 'mariposa', category: 'Animales', variations: [{ text: 'Mariposa', icon: 'mdi:butterfly' }] },

    // Fringe: Juguetes y Objetos
    { id: 'pelota', category: 'Juguetes', variations: [{ text: 'Pelota', icon: 'mdi:soccer' }] },
    { id: 'muneca', category: 'Juguetes', variations: [{ text: 'Muñeca', icon: 'mdi:human-female' }] },
    { id: 'carro', category: 'Juguetes', variations: [{ text: 'Carro', icon: 'mdi:car' }] },
    { id: 'tren', category: 'Juguetes', variations: [{ text: 'Tren', icon: 'mdi:train' }] },
    { id: 'avion', category: 'Juguetes', variations: [{ text: 'Avión', icon: 'mdi:airplane' }] },
    { id: 'barco', category: 'Juguetes', variations: [{ text: 'Barco', icon: 'mdi:boat' }] },
    { id: 'bloques', category: 'Juguetes', variations: [{ text: 'Bloques', icon: 'mdi:toy-brick' }] },
    { id: 'libro', category: 'Juguetes', variations: [{ text: 'Libro', icon: 'mdi:book' }] },
    { id: 'lapiz', category: 'Juguetes', variations: [{ text: 'Lápiz', icon: 'mdi:pencil-box' }] },
    { id: 'crayola', category: 'Juguetes', variations: [{ text: 'Crayola', icon: 'mdi:pen' }] },
    { id: 'tijeras', category: 'Juguetes', variations: [{ text: 'Tijeras', icon: 'mdi:content-cut' }] },
    { id: 'pega', category: 'Juguetes', variations: [{ text: 'Pega', icon: 'mdi:glue-stick' }] },
    { id: 'mesa', category: 'Objetos', variations: [{ text: 'Mesa', icon: 'mdi:table-furniture' }] },
    { id: 'silla', category: 'Objetos', variations: [{ text: 'Silla', icon: 'mdi:chair-rolling' }] },
    { id: 'cama', category: 'Objetos', variations: [{ text: 'Cama', icon: 'mdi:bed' }] },
    { id: 'puerta', category: 'Objetos', variations: [{ text: 'Puerta', icon: 'mdi:door' }] },
    { id: 'ventana', category: 'Objetos', variations: [{ text: 'Ventana', icon: 'mdi:window-maximize' }] },
    { id: 'luz', category: 'Objetos', variations: [{ text: 'Luz', icon: 'mdi:lightbulb' }] },
    { id: 'telefono', category: 'Objetos', variations: [{ text: 'Teléfono', icon: 'mdi:phone' }] },
    { id: 'television', category: 'Objetos', variations: [{ text: 'Televisión', icon: 'mdi:television' }] },
    { id: 'computadora', category: 'Objetos', variations: [{ text: 'Computadora', icon: 'mdi:laptop' }] },
    { id: 'reloj', category: 'Objetos', variations: [{ text: 'Reloj', icon: 'mdi:clock' }] },

    // Fringe: Lugares
    { id: 'casa', category: 'Lugares', variations: [{ text: 'Casa', icon: 'mdi:home' }] },
    { id: 'escuela', category: 'Lugares', variations: [{ text: 'Escuela', icon: 'mdi:school' }] },
    { id: 'parque', category: 'Lugares', variations: [{ text: 'Parque', icon: 'mdi:pine-tree' }] },
    { id: 'tienda', category: 'Lugares', variations: [{ text: 'Tienda', icon: 'mdi:store' }] },
    { id: 'hospital', category: 'Lugares', variations: [{ text: 'Hospital', icon: 'mdi:hospital-building' }] },
    { id: 'playa', category: 'Lugares', variations: [{ text: 'Playa', icon: 'mdi:beach' }] },
    { id: 'piscina', category: 'Lugares', variations: [{ text: 'Piscina', icon: 'mdi:pool' }] },
    { id: 'cine', category: 'Lugares', variations: [{ text: 'Cine', icon: 'mdi:movie' }] },
    { id: 'restaurante', category: 'Lugares', variations: [{ text: 'Restaurante', icon: 'mdi:restaurant' }] },
    { id: 'bano', category: 'Lugares', variations: [{ text: 'Baño', icon: 'mdi:toilet' }] },
    { id: 'cocina', category: 'Lugares', variations: [{ text: 'Cocina', icon: 'mdi:pot-steam' }] },
    { id: 'dormitorio', category: 'Lugares', variations: [{ text: 'Dormitorio', icon: 'mdi:bed-king' }] },
    { id: 'sala', category: 'Lugares', variations: [{ text: 'Sala', icon: 'mdi:sofa' }] },
    { id: 'jardin', category: 'Lugares', variations: [{ text: 'Jardín', icon: 'mdi:flower' }] },

    // Fringe: Emociones y Adjetivos
    { id: 'feliz', category: 'Sentimientos', variations: [{ text: 'Feliz', icon: 'mdi:emoticon-happy' }, { text: 'Felices', icon: 'mdi:emoticon-happy-outline' }] },
    { id: 'triste', category: 'Sentimientos', variations: [{ text: 'Triste', icon: 'mdi:emoticon-sad' }, { text: 'Tristes', icon: 'mdi:emoticon-sad-outline' }] },
    { id: 'enojado', category: 'Sentimientos', variations: [{ text: 'Enojado', icon: 'mdi:emoticon-angry' }, { text: 'Enojados', icon: 'mdi:emoticon-angry-outline' }] },
    { id: 'asustado', category: 'Sentimientos', variations: [{ text: 'Asustado', icon: 'mdi:emoticon-dead' }, { text: 'Asustados', icon: 'mdi:emoticon-dead-outline' }] },
    { id: 'sorprendido', category: 'Sentimientos', variations: [{ text: 'Sorprendido', icon: 'mdi:emoticon-excited' }, { text: 'Sorprendidos', icon: 'mdi:emoticon-excited-outline' }] },
    { id: 'cansado', category: 'Sentimientos', variations: [{ text: 'Cansado', icon: 'mdi:battery-30' }, { text: 'Cansados', icon: 'mdi:battery-10' }] },
    { id: 'enfermo', category: 'Sentimientos', variations: [{ text: 'Enfermo', icon: 'mdi:emoticon-sick' }, { text: 'Enfermos', icon: 'mdi:emoticon-sick-outline' }] },
    { id: 'bien', category: 'Sentimientos', variations: [{ text: 'Bien', icon: 'mdi:thumb-up' }] },
    { id: 'mal', category: 'Sentimientos', variations: [{ text: 'Mal', icon: 'mdi:thumb-down' }] },
    { id: 'frustrado', category: 'Sentimientos', variations: [{ text: 'Frustrado', icon: 'mdi:emoticon-confused' }] },
    { id: 'emocionado', category: 'Sentimientos', variations: [{ text: 'Emocionado', icon: 'mdi:emoticon-cool' }] },
    { id: 'timido', category: 'Sentimientos', variations: [{ text: 'Tímido', icon: 'mdi:emoticon-neutral' }] },
    { id: 'grande', category: 'Conceptos', variations: [{ text: 'Grande', icon: 'mdi:arrow-expand-all' }, { text: 'Grandes', icon: 'mdi:arrow-expand' }] },
    { id: 'pequeno', category: 'Conceptos', variations: [{ text: 'Pequeño', icon: 'mdi:arrow-collapse-all' }, { text: 'Pequeños', icon: 'mdi:arrow-collapse' }] },
    { id: 'caliente', category: 'Conceptos', variations: [{ text: 'Caliente', icon: 'mdi:fire' }] },
    { id: 'frio', category: 'Conceptos', variations: [{ text: 'Frío', icon: 'mdi:snowflake' }] },
    { id: 'rapido', category: 'Conceptos', variations: [{ text: 'Rápido', icon: 'mdi:run-fast' }] },
    { id: 'lento', category: 'Conceptos', variations: [{ text: 'Lento', icon: 'mdi:tortoise' }] },
    { id: 'bonito', category: 'Conceptos', variations: [{ text: 'Bonito', icon: 'mdi:heart' }, { text: 'Bonitos', icon: 'mdi:heart-multiple' }] },
    { id: 'feo', category: 'Conceptos', variations: [{ text: 'Feo', icon: 'mdi:heart-broken' }, { text: 'Feos', icon: 'mdi:heart-broken-outline' }] },
    { id: 'limpio', category: 'Conceptos', variations: [{ text: 'Limpio', icon: 'mdi:clean' }] },
    { id: 'sucio', category: 'Conceptos', variations: [{ text: 'Sucio', icon: 'mdi:dirty' }] },
    { id: 'fuerte', category: 'Conceptos', variations: [{ text: 'Fuerte', icon: 'mdi:arm-flex' }] },
    { id: 'debil', category: 'Conceptos', variations: [{ text: 'Débil', icon: 'mdi:arm-flex-outline' }] },

    // Fringe: Tiempo y Clima
    { id: 'hoy', category: 'Tiempo', variations: [{ text: 'Hoy', icon: 'mdi:calendar-today' }] },
    { id: 'ayer', category: 'Tiempo', variations: [{ text: 'Ayer', icon: 'mdi:calendar-arrow-left' }] },
    { id: 'manana', category: 'Tiempo', variations: [{ text: 'Mañana', icon: 'mdi:calendar-arrow-right' }] },
    { id: 'ahora', category: 'Tiempo', variations: [{ text: 'Ahora', icon: 'mdi:clock-time-eight' }] },
    { id: 'despues', category: 'Tiempo', variations: [{ text: 'Después', icon: 'mdi:arrow-right' }] },
    { id: 'antes', category: 'Tiempo', variations: [{ text: 'Antes', icon: 'mdi:arrow-left' }] },
    { id: 'dia', category: 'Tiempo', variations: [{ text: 'Día', icon: 'mdi:weather-sunny' }] },
    { id: 'noche', category: 'Tiempo', variations: [{ text: 'Noche', icon: 'mdi:weather-night' }] },
    { id: 'sol', category: 'Clima', variations: [{ text: 'Sol', icon: 'mdi:white-balance-sunny' }] },
    { id: 'lluvia', category: 'Clima', variations: [{ text: 'Lluvia', icon: 'mdi:weather-rainy' }] },
    { id: 'nube', category: 'Clima', variations: [{ text: 'Nube', icon: 'mdi:weather-cloudy' }] },
    { id: 'viento', category: 'Clima', variations: [{ text: 'Viento', icon: 'mdi:weather-windy' }] },
    { id: 'nieve', category: 'Clima', variations: [{ text: 'Nieve', icon: 'mdi:weather-snowy' }] },

    // Fringe: Colores
    { id: 'rojo', category: 'Colores', variations: [{ text: 'Rojo', icon: 'mdi:circle', style: { color: 'red' } }] },
    { id: 'azul', category: 'Colores', variations: [{ text: 'Azul', icon: 'mdi:circle', style: { color: 'blue' } }] },
    { id: 'amarillo', category: 'Colores', variations: [{ text: 'Amarillo', icon: 'mdi:circle', style: { color: 'yellow' } }] },
    { id: 'verde', category: 'Colores', variations: [{ text: 'Verde', icon: 'mdi:circle', style: { color: 'green' } }] },
    { id: 'naranja_color', category: 'Colores', variations: [{ text: 'Naranja', icon: 'mdi:circle', style: { color: 'orange' } }] },
    { id: 'morado', category: 'Colores', variations: [{ text: 'Morado', icon: 'mdi:circle', style: { color: 'purple' } }] },
    { id: 'rosado', category: 'Colores', variations: [{ text: 'Rosado', icon: 'mdi:circle', style: { color: 'pink' } }] },
    { id: 'negro', category: 'Colores', variations: [{ text: 'Negro', icon: 'mdi:circle', style: { color: 'black' } }] },
    { id: 'blanco', category: 'Colores', variations: [{ text: 'Blanco', icon: 'mdi:circle-outline', style: { color: 'black' } }] },
    { id: 'gris', category: 'Colores', variations: [{ text: 'Gris', icon: 'mdi:circle-half-full', style: { color: 'gray' } }] },
    { id: 'marron', category: 'Colores', variations: [{ text: 'Marrón', icon: 'mdi:square', style: { color: 'brown' } }] },

    // Fringe: Números
    { id: 'uno', category: 'Números', variations: [{ text: 'Uno', icon: 'mdi:numeric-1-circle' }] },
    { id: 'dos', category: 'Números', variations: [{ text: 'Dos', icon: 'mdi:numeric-2-circle' }] },
    { id: 'tres', category: 'Números', variations: [{ text: 'Tres', icon: 'mdi:numeric-3-circle' }] },
    { id: 'cuatro', category: 'Números', variations: [{ text: 'Cuatro', icon: 'mdi:numeric-4-circle' }] },
    { id: 'cinco', category: 'Números', variations: [{ text: 'Cinco', icon: 'mdi:numeric-5-circle' }] },
    { id: 'seis', category: 'Números', variations: [{ text: 'Seis', icon: 'mdi:numeric-6-circle' }] },
    { id: 'siete', category: 'Números', variations: [{ text: 'Siete', icon: 'mdi:numeric-7-circle' }] },
    { id: 'ocho', category: 'Números', variations: [{ text: 'Ocho', icon: 'mdi:numeric-8-circle' }] },
    { id: 'nueve', category: 'Números', variations: [{ text: 'Nueve', icon: 'mdi:numeric-9-circle' }] },
    { id: 'diez', category: 'Números', variations: [{ text: 'Diez', icon: 'mdi:numeric-10-circle' }] },
];
