const categoryData = {
    'Emociones': { icon: 'mdi:emoticon-happy-outline' },
    'Acciones': { icon: 'mdi:run' },
    'Objetos': { icon: 'mdi:lightbulb-on-outline' },
    'Lugares': { icon: 'mdi:map-marker-radius-outline' },
    'Personas': { icon: 'mdi:account-group-outline' },
    'Animales': { icon: 'mdi:dog' },
    'Comida y bebida': { icon: 'mdi:food-apple-outline' },
    'Ropa y accesorios': { icon: 'mdi:tshirt-crew-outline' },
    'Tecnología y medios': { icon: 'mdi:cellphone' },
    'Cuerpo y salud': { icon: 'mdi:heart-pulse' },
    'Tiempo y clima': { icon: 'mdi:calendar-clock' },
    'Escuela y aprendizaje': { icon: 'mdi:school-outline' },
    'Familia y relaciones': { icon: 'mdi:human-male-female-child' },
    'Transporte y viaje': { icon: 'mdi:car-outline' },
    'Rutinas y actividades diarias': { icon: 'mdi:toothbrush' },
    'Verbos básicos': { icon: 'mdi:alpha-v-box-outline' },
    'Negación y afirmación': { icon: 'mdi:check-decagram-outline' },
    'Colores, formas y números': { icon: 'mdi:palette-outline' },
    'Celebraciones y cultura': { icon: 'mdi:party-popper' },
    'Señales y símbolos': { icon: 'mdi:alert-circle-outline' }
};

const pictogramData = [
    // Emociones
    { id: 'feliz', category: 'Emociones', variations: [{ text: 'Feliz', icon: 'mdi:emoticon-happy' }], nouns: ['felicidad', 'alegría'], synonyms: ['alegre', 'contento'], antonyms: ['triste'] },
    { id: 'triste', category: 'Emociones', variations: [{ text: 'Triste', icon: 'mdi:emoticon-sad' }], nouns: ['tristeza', 'pena'], synonyms: ['apenado', 'melancólico'], antonyms: ['feliz'] },
    { id: 'enojado', category: 'Emociones', variations: [{ text: 'Enojado', icon: 'mdi:emoticon-angry' }], nouns: ['enojo', 'ira'], synonyms: ['enfadado', 'molesto'], antonyms: ['contento'] },
    { id: 'miedo', category: 'Emociones', variations: [{ text: 'Miedo', icon: 'mdi:emoticon-dead' }], nouns: ['miedo', 'temor'], synonyms: ['pavor', 'terror'], antonyms: ['valentía'] },
    { id: 'sorpresa', category: 'Emociones', variations: [{ text: 'Sorpresa', icon: 'mdi:emoticon-excited' }], nouns: ['sorpresa', 'asombro'], synonyms: ['asombro', 'pasmado'], antonyms: [] },
    { id: 'calma', category: 'Emociones', variations: [{ text: 'Calma', icon: 'mdi:emoticon-cool' }], nouns: ['calma', 'tranquilidad'], synonyms: ['tranquilidad', 'paz'], antonyms: ['ansiedad'] },
    { id: 'ansiedad', category: 'Emociones', variations: [{ text: 'Ansiedad', icon: 'mdi:emoticon-confused' }], nouns: ['ansiedad', 'inquietud'], synonyms: ['inquietud', 'nerviosismo'], antonyms: ['calma'] },
    { id: 'frustracion', category: 'Emociones', variations: [{ text: 'Frustración', icon: 'mdi:emoticon-cry' }], nouns: ['frustración', 'decepción'], synonyms: ['decepción', 'desilusión'], antonyms: ['satisfacción'] },

    // Acciones
    { id: 'correr', category: 'Acciones', variations: [{ text: 'Correr', icon: 'mdi:run-fast' }], nouns: ['carrera'], synonyms: ['trotar', 'galopar'], antonyms: ['detenerse'] },
    { id: 'saltar', category: 'Acciones', variations: [{ text: 'Saltar', icon: 'mdi:human-jump' }], nouns: ['salto'], synonyms: ['brincar', 'botar'], antonyms: [] },
    { id: 'dormir', category: 'Acciones', variations: [{ text: 'Dormir', icon: 'mdi:sleep' }], nouns: ['sueño'], synonyms: ['descansar', 'reposar'], antonyms: ['despertar'] },
    { id: 'comer', category: 'Acciones', variations: [{ text: 'Comer', icon: 'mdi:food' }], nouns: ['comida'], synonyms: ['alimentarse', 'ingerir'], antonyms: ['ayunar'] },
    { id: 'leer', category: 'Acciones', variations: [{ text: 'Leer', icon: 'mdi:book-open-page-variant' }], nouns: ['lectura'], synonyms: ['interpretar', 'descifrar'], antonyms: ['escribir'] },
    { id: 'escribir', category: 'Acciones', variations: [{ text: 'Escribir', icon: 'mdi:pencil' }], nouns: ['escritura'], synonyms: ['redactar', 'anotar'], antonyms: ['leer'] },
    { id: 'jugar', category: 'Acciones', variations: [{ text: 'Jugar', icon: 'mdi:gamepad-variant' }], nouns: ['juego'], synonyms: ['entretenerse', 'recrearse'], antonyms: ['trabajar'] },
    { id: 'trabajar', category: 'Acciones', variations: [{ text: 'Trabajar', icon: 'mdi:briefcase' }], nouns: ['trabajo'], synonyms: ['laborar', 'operar'], antonyms: ['descansar'] },
    { id: 'bailar', category: 'Acciones', variations: [{ text: 'Bailar', icon: 'mdi:dance-ballroom' }], nouns: ['baile'], synonyms: ['danzar', 'moverse'], antonyms: [] },
    { id: 'mirar', category: 'Acciones', variations: [{ text: 'Mirar', icon: 'mdi:eye' }], nouns: ['mirada'], synonyms: ['observar', 'ver'], antonyms: ['ignorar'] },

    // Objetos
    { id: 'silla', category: 'Objetos', variations: [{ text: 'Silla', icon: 'mdi:chair-rolling' }], nouns: ['silla', 'asiento'], synonyms: ['asiento'], antonyms: [] },
    { id: 'cuchara', category: 'Objetos', variations: [{ text: 'Cuchara', icon: 'mdi:spoon-sugar' }], nouns: ['cuchara', 'cubierto'], synonyms: [], antonyms: [] },
    { id: 'pelota', category: 'Objetos', variations: [{ text: 'Pelota', icon: 'mdi:soccer' }], nouns: ['pelota', 'balón'], synonyms: ['balón'], antonyms: [] },
    { id: 'lapiz', category: 'Objetos', variations: [{ text: 'Lápiz', icon: 'mdi:pencil-box' }], nouns: ['lápiz', 'utensilio'], synonyms: [], antonyms: [] },
    { id: 'mochila', category: 'Objetos', variations: [{ text: 'Mochila', icon: 'mdi:bag-personal' }], nouns: ['mochila', 'bolso'], synonyms: ['bolso'], antonyms: [] },
    { id: 'celular', category: 'Objetos', variations: [{ text: 'Celular', icon: 'mdi:cellphone' }], nouns: ['celular', 'teléfono'], synonyms: ['teléfono', 'móvil'], antonyms: [] },
    { id: 'libro', category: 'Objetos', variations: [{ text: 'Libro', icon: 'mdi:book' }], nouns: ['libro', 'obra'], synonyms: [], antonyms: [] },
    { id: 'vaso', category: 'Objetos', variations: [{ text: 'Vaso', icon: 'mdi:cup' }], nouns: ['vaso', 'recipiente'], synonyms: [], antonyms: [] },
    { id: 'cama', category: 'Objetos', variations: [{ text: 'Cama', icon: 'mdi:bed' }], nouns: ['cama', 'lecho'], synonyms: ['lecho'], antonyms: [] },
    { id: 'paraguas', category: 'Objetos', variations: [{ text: 'Paraguas', icon: 'mdi:umbrella' }], nouns: ['paraguas', 'sombrilla'], synonyms: ['sombrilla'], antonyms: [] },

    // Lugares
    { id: 'casa', category: 'Lugares', variations: [{ text: 'Casa', icon: 'mdi:home' }], nouns: ['casa', 'hogar'], synonyms: ['hogar', 'vivienda'], antonyms: [] },
    { id: 'colegio', category: 'Lugares', variations: [{ text: 'Colegio', icon: 'mdi:school' }], nouns: ['colegio', 'escuela'], synonyms: ['escuela', 'instituto'], antonyms: [] },
    { id: 'parque', category: 'Lugares', variations: [{ text: 'Parque', icon: 'mdi:pine-tree' }], nouns: ['parque', 'jardín'], synonyms: ['jardín'], antonyms: [] },
    { id: 'hospital', category: 'Lugares', variations: [{ text: 'Hospital', icon: 'mdi:hospital-building' }], nouns: ['hospital', 'clínica'], synonyms: ['clínica', 'sanatorio'], antonyms: [] },
    { id: 'bano', category: 'Lugares', variations: [{ text: 'Baño', icon: 'mdi:toilet' }], nouns: ['baño', 'aseo'], synonyms: ['aseo', 'servicio'], antonyms: [] },
    { id: 'cocina', category: 'Lugares', variations: [{ text: 'Cocina', icon: 'mdi:pot-steam' }], nouns: ['cocina'], synonyms: [], antonyms: [] },
    { id: 'tienda', category: 'Lugares', variations: [{ text: 'Tienda', icon: 'mdi:store' }], nouns: ['tienda', 'comercio'], synonyms: ['comercio', 'negocio'], antonyms: [] },
    { id: 'playa', category: 'Lugares', variations: [{ text: 'Playa', icon: 'mdi:beach' }], nouns: ['playa', 'costa'], synonyms: ['costa'], antonyms: [] },
    { id: 'cine', category: 'Lugares', variations: [{ text: 'Cine', icon: 'mdi:movie' }], nouns: ['cine', 'sala de cine'], synonyms: [], antonyms: [] },
    { id: 'iglesia', category: 'Lugares', variations: [{ text: 'Iglesia', icon: 'mdi:church' }], nouns: ['iglesia', 'templo'], synonyms: ['templo'], antonyms: [] },

    // Personas
    { id: 'mama', category: 'Personas', variations: [{ text: 'Mamá', icon: 'mdi:human-female-boy' }], nouns: ['madre'], synonyms: ['mamá', 'madre'], antonyms: [] },
    { id: 'papa', category: 'Personas', variations: [{ text: 'Papá', icon: 'mdi:human-male-girl' }], nouns: ['padre'], synonyms: ['papá', 'padre'], antonyms: [] },
    { id: 'maestro', category: 'Personas', variations: [{ text: 'Maestro', icon: 'mdi:teach' }], nouns: ['maestro', 'profesor'], synonyms: ['profesor', 'docente'], antonyms: ['alumno'] },
    { id: 'doctor', category: 'Personas', variations: [{ text: 'Doctor', icon: 'mdi:doctor' }], nouns: ['doctor', 'médico'], synonyms: ['médico', 'galeno'], antonyms: [] },
    { id: 'amigo', category: 'Personas', variations: [{ text: 'Amigo', icon: 'mdi:account-heart' }], nouns: ['amigo', 'compañero'], synonyms: ['compañero', 'camarada'], antonyms: ['enemigo'] },
    { id: 'nina', category: 'Personas', variations: [{ text: 'Niña', icon: 'mdi:human-female-girl' }], nouns: ['niña', 'chica'], synonyms: ['chica', 'pequeña'], antonyms: ['adulta'] },
    { id: 'nino', category: 'Personas', variations: [{ text: 'Niño', icon: 'mdi:human-child' }], nouns: ['niño', 'chico'], synonyms: ['chico', 'pequeño'], antonyms: ['adulto'] },
    { id: 'policia', category: 'Personas', variations: [{ text: 'Policía', icon: 'mdi:police-badge' }], nouns: ['policía', 'agente'], synonyms: ['agente'], antonyms: [] },
    { id: 'abuelos', category: 'Personas', variations: [{ text: 'Abuelos', icon: 'mdi:human-male-female' }], nouns: ['abuelos'], synonyms: [], antonyms: [] },
    { id: 'yo', category: 'Personas', variations: [{ text: 'Yo', icon: 'mdi:account' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'tu', category: 'Personas', variations: [{ text: 'Tú', icon: 'mdi:account-outline' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'nosotros', category: 'Personas', variations: [{ text: 'Nosotros', icon: 'mdi:account-group' }], nouns: [], synonyms: [], antonyms: [] },

    // Animales
    { id: 'perro', category: 'Animales', variations: [{ text: 'Perro', icon: 'mdi:dog-side' }], nouns: ['perro', 'can'], synonyms: ['can'], antonyms: [] },
    { id: 'gato', category: 'Animales', variations: [{ text: 'Gato', icon: 'mdi:cat' }], nouns: ['gato', 'felino'], synonyms: ['felino'], antonyms: [] },
    { id: 'pajaro', category: 'Animales', variations: [{ text: 'Pájaro', icon: 'mdi:bird' }], nouns: ['pájaro', 'ave'], synonyms: ['ave'], antonyms: [] },
    { id: 'pez', category: 'Animales', variations: [{ text: 'Pez', icon: 'mdi:fish' }], nouns: ['pez', 'pescado'], synonyms: [], antonyms: [] },
    { id: 'vaca', category: 'Animales', variations: [{ text: 'Vaca', icon: 'mdi:cow' }], nouns: ['vaca', 'bovino'], synonyms: [], antonyms: [] },
    { id: 'caballo', category: 'Animales', variations: [{ text: 'Caballo', icon: 'mdi:horse' }], nouns: ['caballo', 'equino'], synonyms: ['equino'], antonyms: [] },
    { id: 'rana', category: 'Animales', variations: [{ text: 'Rana', icon: 'mdi:frog' }], nouns: ['rana', 'anfibio'], synonyms: [], antonyms: [] },
    { id: 'leon', category: 'Animales', variations: [{ text: 'León', icon: 'mdi:lion' }], nouns: ['león', 'felino'], synonyms: [], antonyms: [] },
    { id: 'elefante', category: 'Animales', variations: [{ text: 'Elefante', icon: 'mdi:elephant' }], nouns: ['elefante'], synonyms: [], antonyms: [] },

    // Comida y bebida
    { id: 'pan', category: 'Comida y bebida', variations: [{ text: 'Pan', icon: 'mdi:bread-slice' }], nouns: ['pan'], synonyms: [], antonyms: [] },
    { id: 'arroz', category: 'Comida y bebida', variations: [{ text: 'Arroz', icon: 'mdi:rice' }], nouns: ['arroz'], synonyms: [], antonyms: [] },
    { id: 'leche', category: 'Comida y bebida', variations: [{ text: 'Leche', icon: 'mdi:cup-water' }], nouns: ['leche'], synonyms: [], antonyms: [] },
    { id: 'manzana', category: 'Comida y bebida', variations: [{ text: 'Manzana', icon: 'mdi:food-apple' }], nouns: ['manzana'], synonyms: [], antonyms: [] },
    { id: 'jugo', category: 'Comida y bebida', variations: [{ text: 'Jugo', icon: 'mdi:food-fork-drink' }], nouns: ['jugo', 'zumo'], synonyms: ['zumo'], antonyms: [] },
    { id: 'sopa', category: 'Comida y bebida', variations: [{ text: 'Sopa', icon: 'mdi:bowl-mix' }], nouns: ['sopa', 'caldo'], synonyms: ['caldo'], antonyms: [] },
    { id: 'carne', category: 'Comida y bebida', variations: [{ text: 'Carne', icon: 'mdi:food-steak' }], nouns: ['carne'], synonyms: [], antonyms: [] },
    { id: 'galleta', category: 'Comida y bebida', variations: [{ text: 'Galleta', icon: 'mdi:cookie' }], nouns: ['galleta'], synonyms: [], antonyms: [] },
    { id: 'agua', category: 'Comida y bebida', variations: [{ text: 'Agua', icon: 'mdi:cup' }], nouns: ['agua'], synonyms: [], antonyms: [] },
    { id: 'helado', category: 'Comida y bebida', variations: [{ text: 'Helado', icon: 'mdi:ice-cream' }], nouns: ['helado'], synonyms: [], antonyms: [] },

    // Ropa y accesorios
    { id: 'camisa', category: 'Ropa y accesorios', variations: [{ text: 'Camisa', icon: 'mdi:tshirt-crew' }], nouns: ['camisa'], synonyms: [], antonyms: [] },
    { id: 'pantalon', category: 'Ropa y accesorios', variations: [{ text: 'Pantalón', icon: 'mdi:pants' }], nouns: ['pantalón'], synonyms: [], antonyms: [] },
    { id: 'zapatos', category: 'Ropa y accesorios', variations: [{ text: 'Zapatos', icon: 'mdi:shoe-sneaker' }], nouns: ['zapato'], synonyms: [], antonyms: [] },
    { id: 'gorra', category: 'Ropa y accesorios', variations: [{ text: 'Gorra', icon: 'mdi:hat-fedora' }], nouns: ['gorra'], synonyms: [], antonyms: [] },
    { id: 'abrigo', category: 'Ropa y accesorios', variations: [{ text: 'Abrigo', icon: 'mdi:jacket' }], nouns: ['abrigo'], synonyms: [], antonyms: [] },
    { id: 'guantes', category: 'Ropa y accesorios', variations: [{ text: 'Guantes', icon: 'mdi:glove' }], nouns: ['guante'], synonyms: [], antonyms: [] },
    { id: 'mochila_ropa', category: 'Ropa y accesorios', variations: [{ text: 'Mochila', icon: 'mdi:bag-personal' }], nouns: ['mochila'], synonyms: [], antonyms: [] },
    { id: 'paraguas_ropa', category: 'Ropa y accesorios', variations: [{ text: 'Paraguas', icon: 'mdi:umbrella' }], nouns: ['paraguas'], synonyms: [], antonyms: [] },

    // Tecnología y medios
    { id: 'celular_tech', category: 'Tecnología y medios', variations: [{ text: 'Celular', icon: 'mdi:cellphone' }], nouns: ['celular'], synonyms: [], antonyms: [] },
    { id: 'computadora', category: 'Tecnología y medios', variations: [{ text: 'Computadora', icon: 'mdi:laptop' }], nouns: ['computadora'], synonyms: [], antonyms: [] },
    { id: 'tablet', category: 'Tecnología y medios', variations: [{ text: 'Tablet', icon: 'mdi:tablet' }], nouns: ['tablet'], synonyms: [], antonyms: [] },
    { id: 'television', category: 'Tecnología y medios', variations: [{ text: 'Televisión', icon: 'mdi:television' }], nouns: ['televisión'], synonyms: [], antonyms: [] },
    { id: 'internet', category: 'Tecnología y medios', variations: [{ text: 'Internet', icon: 'mdi:web' }], nouns: ['internet'], synonyms: [], antonyms: [] },
    { id: 'camara', category: 'Tecnología y medios', variations: [{ text: 'Cámara', icon: 'mdi:camera' }], nouns: ['cámara'], synonyms: [], antonyms: [] },
    { id: 'llamada', category: 'Tecnología y medios', variations: [{ text: 'Llamada', icon: 'mdi:phone' }], nouns: ['llamada'], synonyms: [], antonyms: [] },
    { id: 'videojuego', category: 'Tecnología y medios', variations: [{ text: 'Videojuego', icon: 'mdi:gamepad-variant' }], nouns: ['videojuego'], synonyms: [], antonyms: [] },

    // Cuerpo y salud
    { id: 'cabeza', category: 'Cuerpo y salud', variations: [{ text: 'Cabeza', icon: 'mdi:head' }], nouns: ['cabeza'], synonyms: [], antonyms: [] },
    { id: 'manos', category: 'Cuerpo y salud', variations: [{ text: 'Manos', icon: 'mdi:hand-wave' }], nouns: ['mano'], synonyms: [], antonyms: [] },
    { id: 'ojos', category: 'Cuerpo y salud', variations: [{ text: 'Ojos', icon: 'mdi:eye' }], nouns: ['ojo'], synonyms: [], antonyms: [] },
    { id: 'boca', category: 'Cuerpo y salud', variations: [{ text: 'Boca', icon: 'mdi:mouth' }], nouns: ['boca'], synonyms: [], antonyms: [] },
    { id: 'pies', category: 'Cuerpo y salud', variations: [{ text: 'Pies', icon: 'mdi:foot-print' }], nouns: ['pie'], synonyms: [], antonyms: [] },
    { id: 'dolor', category: 'Cuerpo y salud', variations: [{ text: 'Dolor', icon: 'mdi:emoticon-cry' }], nouns: ['dolor'], synonyms: [], antonyms: [] },
    { id: 'medicina', category: 'Cuerpo y salud', variations: [{ text: 'Medicina', icon: 'mdi:pill' }], nouns: ['medicina'], synonyms: [], antonyms: [] },
    { id: 'doctor_salud', category: 'Cuerpo y salud', variations: [{ text: 'Doctor', icon: 'mdi:doctor' }], nouns: ['doctor'], synonyms: [], antonyms: [] },
    { id: 'enfermo', category: 'Cuerpo y salud', variations: [{ text: 'Enfermo', icon: 'mdi:emoticon-sick' }], nouns: ['enfermo'], synonyms: [], antonyms: [] },
    { id: 'termometro', category: 'Cuerpo y salud', variations: [{ text: 'Termómetro', icon: 'mdi:thermometer' }], nouns: ['termómetro'], synonyms: [], antonyms: [] },
    { id: 'higiene', category: 'Cuerpo y salud', variations: [{ text: 'Higiene', icon: 'mdi:hand-water' }], nouns: ['higiene'], synonyms: [], antonyms: [] },

    // Tiempo y clima
    { id: 'ayer', category: 'Tiempo y clima', variations: [{ text: 'Ayer', icon: 'mdi:calendar-arrow-left' }], nouns: ['ayer'], synonyms: [], antonyms: [] },
    { id: 'hoy', category: 'Tiempo y clima', variations: [{ text: 'Hoy', icon: 'mdi:calendar-today' }], nouns: ['hoy'], synonyms: [], antonyms: [] },
    { id: 'manana', category: 'Tiempo y clima', variations: [{ text: 'Mañana', icon: 'mdi:calendar-arrow-right' }], nouns: ['mañana'], synonyms: [], antonyms: [] },
    { id: 'hora', category: 'Tiempo y clima', variations: [{ text: 'Hora', icon: 'mdi:clock' }], nouns: ['hora'], synonyms: [], antonyms: [] },
    { id: 'tarde', category: 'Tiempo y clima', variations: [{ text: 'Tarde', icon: 'mdi:weather-sunset' }], nouns: ['tarde'], synonyms: [], antonyms: [] },
    { id: 'noche', category: 'Tiempo y clima', variations: [{ text: 'Noche', icon: 'mdi:weather-night' }], nouns: ['noche'], synonyms: [], antonyms: [] },
    { id: 'sol', category: 'Tiempo y clima', variations: [{ text: 'Sol', icon: 'mdi:weather-sunny' }], nouns: ['sol'], synonyms: [], antonyms: [] },
    { id: 'lluvia', category: 'Tiempo y clima', variations: [{ text: 'Lluvia', icon: 'mdi:weather-rainy' }], nouns: ['lluvia'], synonyms: [], antonyms: [] },
    { id: 'frio', category: 'Tiempo y clima', variations: [{ text: 'Frío', icon: 'mdi:snowflake' }], nouns: ['frío'], synonyms: [], antonyms: [] },
    { id: 'calor', category: 'Tiempo y clima', variations: [{ text: 'Calor', icon: 'mdi:fire' }], nouns: ['calor'], synonyms: [], antonyms: [] },
    { id: 'viento', category: 'Tiempo y clima', variations: [{ text: 'Viento', icon: 'mdi:weather-windy' }], nouns: ['viento'], synonyms: [], antonyms: [] },

    // Escuela y aprendizaje
    { id: 'aula', category: 'Escuela y aprendizaje', variations: [{ text: 'Aula', icon: 'mdi:school' }], nouns: ['aula'], synonyms: [], antonyms: [] },
    { id: 'tarea', category: 'Escuela y aprendizaje', variations: [{ text: 'Tarea', icon: 'mdi:notebook-edit' }], nouns: ['tarea'], synonyms: [], antonyms: [] },
    { id: 'profesor', category: 'Escuela y aprendizaje', variations: [{ text: 'Profesor', icon: 'mdi:teach' }], nouns: ['profesor'], synonyms: [], antonyms: [] },
    { id: 'alumno', category: 'Escuela y aprendizaje', variations: [{ text: 'Alumno', icon: 'mdi:account-school' }], nouns: ['alumno'], synonyms: [], antonyms: [] },
    { id: 'examen', category: 'Escuela y aprendizaje', variations: [{ text: 'Examen', icon: 'mdi:file-document-edit' }], nouns: ['examen'], synonyms: [], antonyms: [] },
    { id: 'cuaderno', category: 'Escuela y aprendizaje', variations: [{ text: 'Cuaderno', icon: 'mdi:notebook' }], nouns: ['cuaderno'], synonyms: [], antonyms: [] },
    { id: 'leer_escuela', category: 'Escuela y aprendizaje', variations: [{ text: 'Leer', icon: 'mdi:book-open-page-variant' }], nouns: ['leer'], synonyms: [], antonyms: [] },
    { id: 'escribir_escuela', category: 'Escuela y aprendizaje', variations: [{ text: 'Escribir', icon: 'mdi:pencil' }], nouns: ['escribir'], synonyms: [], antonyms: [] },
    { id: 'pintar_escuela', category: 'Escuela y aprendizaje', variations: [{ text: 'Pintar', icon: 'mdi:palette' }], nouns: ['pintar'], synonyms: [], antonyms: [] },
    { id: 'reglas', category: 'Escuela y aprendizaje', variations: [{ text: 'Reglas', icon: 'mdi:ruler' }], nouns: ['reglas'], synonyms: [], antonyms: [] },

    // Familia y relaciones
    { id: 'mama_familia', category: 'Familia y relaciones', variations: [{ text: 'Mamá', icon: 'mdi:human-female-boy' }], nouns: ['mamá'], synonyms: [], antonyms: [] },
    { id: 'papa_familia', category: 'Familia y relaciones', variations: [{ text: 'Papá', icon: 'mdi:human-male-girl' }], nouns: ['papá'], synonyms: [], antonyms: [] },
    { id: 'hermano', category: 'Familia y relaciones', variations: [{ text: 'Hermano', icon: 'mdi:human-male-male' }], nouns: ['hermano'], synonyms: [], antonyms: [] },
    { id: 'amigo_familia', category: 'Familia y relaciones', variations: [{ text: 'Amigo', icon: 'mdi:account-heart' }], nouns: ['amigo'], synonyms: [], antonyms: [] },
    { id: 'vecino', category: 'Familia y relaciones', variations: [{ text: 'Vecino', icon: 'mdi:home-account' }], nouns: ['vecino'], synonyms: [], antonyms: [] },
    { id: 'pareja', category: 'Familia y relaciones', variations: [{ text: 'Pareja', icon: 'mdi:heart' }], nouns: ['pareja'], synonyms: [], antonyms: [] },
    { id: 'tio', category: 'Familia y relaciones', variations: [{ text: 'Tío', icon: 'mdi:human-male' }], nouns: ['tío'], synonyms: [], antonyms: [] },
    { id: 'primo', category: 'Familia y relaciones', variations: [{ text: 'Primo', icon: 'mdi:human-child' }], nouns: ['primo'], synonyms: [], antonyms: [] },
    { id: 'companero', category: 'Familia y relaciones', variations: [{ text: 'Compañero', icon: 'mdi:account-multiple' }], nouns: ['compañero'], synonyms: [], antonyms: [] },

    // Transporte y viaje
    { id: 'auto', category: 'Transporte y viaje', variations: [{ text: 'Auto', icon: 'mdi:car' }], nouns: ['auto'], synonyms: [], antonyms: [] },
    { id: 'bus', category: 'Transporte y viaje', variations: [{ text: 'Bus', icon: 'mdi:bus' }], nouns: ['bus'], synonyms: [], antonyms: [] },
    { id: 'bicicleta', category: 'Transporte y viaje', variations: [{ text: 'Bicicleta', icon: 'mdi:bike' }], nouns: ['bicicleta'], synonyms: [], antonyms: [] },
    { id: 'tren', category: 'Transporte y viaje', variations: [{ text: 'Tren', icon: 'mdi:train' }], nouns: ['tren'], synonyms: [], antonyms: [] },
    { id: 'avion', category: 'Transporte y viaje', variations: [{ text: 'Avión', icon: 'mdi:airplane' }], nouns: ['avión'], synonyms: [], antonyms: [] },
    { id: 'semaforo', category: 'Transporte y viaje', variations: [{ text: 'Semáforo', icon: 'mdi:traffic-light' }], nouns: ['semáforo'], synonyms: [], antonyms: [] },
    { id: 'calle', category: 'Transporte y viaje', variations: [{ text: 'Calle', icon: 'mdi:road-variant' }], nouns: ['calle'], synonyms: [], antonyms: [] },
    { id: 'puente', category: 'Transporte y viaje', variations: [{ text: 'Puente', icon: 'mdi:bridge' }], nouns: ['puente'], synonyms: [], antonyms: [] },
    { id: 'senal_transito', category: 'Transporte y viaje', variations: [{ text: 'Señal de tránsito', icon: 'mdi:sign-traffic' }], nouns: ['señal de tránsito'], synonyms: [], antonyms: [] },

    // Rutinas y actividades diarias
    { id: 'cepillarse', category: 'Rutinas y actividades diarias', variations: [{ text: 'Cepillarse', icon: 'mdi:toothbrush' }], nouns: ['cepillarse'], synonyms: [], antonyms: [] },
    { id: 'banarse', category: 'Rutinas y actividades diarias', variations: [{ text: 'Bañarse', icon: 'mdi:shower' }], nouns: ['bañarse'], synonyms: [], antonyms: [] },
    { id: 'vestirse', category: 'Rutinas y actividades diarias', variations: [{ text: 'Vestirse', icon: 'mdi:tshirt-crew' }], nouns: ['vestirse'], synonyms: [], antonyms: [] },
    { id: 'dormir_rutina', category: 'Rutinas y actividades diarias', variations: [{ text: 'Dormir', icon: 'mdi:sleep' }], nouns: ['dormir'], synonyms: [], antonyms: [] },
    { id: 'despertarse', category: 'Rutinas y actividades diarias', variations: [{ text: 'Despertarse', icon: 'mdi:weather-sunny' }], nouns: ['despertarse'], synonyms: [], antonyms: [] },
    { id: 'comer_rutina', category: 'Rutinas y actividades diarias', variations: [{ text: 'Comer', icon: 'mdi:food' }], nouns: ['comer'], synonyms: [], antonyms: [] },
    { id: 'jugar_rutina', category: 'Rutinas y actividades diarias', variations: [{ text: 'Jugar', icon: 'mdi:gamepad-variant' }], nouns: ['jugar'], synonyms: [], antonyms: [] },
    { id: 'ir_al_bano', category: 'Rutinas y actividades diarias', variations: [{ text: 'Ir al baño', icon: 'mdi:toilet' }], nouns: ['ir al baño'], synonyms: [], antonyms: [] },
    { id: 'lavarse_manos', category: 'Rutinas y actividades diarias', variations: [{ text: 'Lavarse las manos', icon: 'mdi:hand-water' }], nouns: ['lavarse las manos'], synonyms: [], antonyms: [] },

    // Verbos básicos
    { id: 'ser', category: 'Verbos básicos', variations: [{ text: 'Ser', icon: 'mdi:alpha-s-box' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'estar', category: 'Verbos básicos', variations: [{ text: 'Estar', icon: 'mdi:alpha-e-box' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'tener', category: 'Verbos básicos', variations: [{ text: 'Tener', icon: 'mdi:alpha-t-box' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'hacer', category: 'Verbos básicos', variations: [{ text: 'Hacer', icon: 'mdi:alpha-h-box' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'querer', category: 'Verbos básicos', variations: [{ text: 'Querer', icon: 'mdi:hand-heart' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'ir', category: 'Verbos básicos', variations: [{ text: 'Ir', icon: 'mdi:arrow-right-bold-circle' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'venir', category: 'Verbos básicos', variations: [{ text: 'Venir', icon: 'mdi:arrow-left-bold-circle' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'decir', category: 'Verbos básicos', variations: [{ text: 'Decir', icon: 'mdi:message-text' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'poder', category: 'Verbos básicos', variations: [{ text: 'Poder', icon: 'mdi:arm-flex' }], nouns: [], synonyms: [], antonyms: [] },

    // Negación y afirmación
    { id: 'si', category: 'Negación y afirmación', variations: [{ text: 'Sí', icon: 'mdi:check' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'no', category: 'Negación y afirmación', variations: [{ text: 'No', icon: 'mdi:close' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'tal_vez', category: 'Negación y afirmación', variations: [{ text: 'Tal vez', icon: 'mdi:help-circle' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'nunca', category: 'Negación y afirmación', variations: [{ text: 'Nunca', icon: 'mdi:cancel' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'siempre', category: 'Negación y afirmación', variations: [{ text: 'Siempre', icon: 'mdi:infinity' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'nada', category: 'Negación y afirmación', variations: [{ text: 'Nada', icon: 'mdi:emoticon-sad' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'todo', category: 'Negación y afirmación', variations: [{ text: 'Todo', icon: 'mdi:earth' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'nadie', category: 'Negación y afirmación', variations: [{ text: 'Nadie', icon: 'mdi:account-off' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'alguien', category: 'Negación y afirmación', variations: [{ text: 'Alguien', icon: 'mdi:account-question' }], nouns: [], synonyms: [], antonyms: [] },

    // Colores, formas y números
    { id: 'rojo', category: 'Colores, formas y números', variations: [{ text: 'Rojo', icon: 'mdi:circle', style: { color: 'red' } }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'azul', category: 'Colores, formas y números', variations: [{ text: 'Azul', icon: 'mdi:circle', style: { color: 'blue' } }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'circulo', category: 'Colores, formas y números', variations: [{ text: 'Círculo', icon: 'mdi:circle-outline' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'cuadrado', category: 'Colores, formas y números', variations: [{ text: 'Cuadrado', icon: 'mdi:square-outline' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'uno', category: 'Colores, formas y números', variations: [{ text: 'Uno', icon: 'mdi:numeric-1-circle' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'dos', category: 'Colores, formas y números', variations: [{ text: 'Dos', icon: 'mdi:numeric-2-circle' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'mucho', category: 'Colores, formas y números', variations: [{ text: 'Mucho', icon: 'mdi:arrow-up-bold-box-outline' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'poco', category: 'Colores, formas y números', variations: [{ text: 'Poco', icon: 'mdi:arrow-down-bold-box-outline' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'mas_menos', category: 'Colores, formas y números', variations: [{ text: 'Más/Menos', icon: 'mdi:plus-minus-variant' }], nouns: [], synonyms: [], antonyms: [] },

    // Celebraciones y cultura
    { id: 'cumpleanos', category: 'Celebraciones y cultura', variations: [{ text: 'Cumpleaños', icon: 'mdi:cake-variant' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'navidad', category: 'Celebraciones y cultura', variations: [{ text: 'Navidad', icon: 'mdi:pine-tree' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'halloween', category: 'Celebraciones y cultura', variations: [{ text: 'Halloween', icon: 'mdi:ghost' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'ano_nuevo', category: 'Celebraciones y cultura', variations: [{ text: 'Año Nuevo', icon: 'mdi:party-popper' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'bandera', category: 'Celebraciones y cultura', variations: [{ text: 'Bandera', icon: 'mdi:flag' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'baile_cultura', category: 'Celebraciones y cultura', variations: [{ text: 'Baile', icon: 'mdi:dance-ballroom' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'tradicion', category: 'Celebraciones y cultura', variations: [{ text: 'Tradición', icon: 'mdi:gavel' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'regalo', category: 'Celebraciones y cultura', variations: [{ text: 'Regalo', icon: 'mdi:gift' }], nouns: [], synonyms: [], antonyms: [] },

    // Señales y símbolos
    { id: 'stop', category: 'Señales y símbolos', variations: [{ text: 'Stop', icon: 'mdi:stop-circle' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'prohibido', category: 'Señales y símbolos', variations: [{ text: 'Prohibido', icon: 'mdi:cancel' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'permitido', category: 'Señales y símbolos', variations: [{ text: 'Permitido', icon: 'mdi:check-circle' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'peligro', category: 'Señales y símbolos', variations: [{ text: 'Peligro', icon: 'mdi:alert' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'informacion', category: 'Señales y símbolos', variations: [{ text: 'Información', icon: 'mdi:information' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'salida', category: 'Señales y símbolos', variations: [{ text: 'Salida', icon: 'mdi:exit-run' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'entrada', category: 'Señales y símbolos', variations: [{ text: 'Entrada', icon: 'mdi:door-open' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'ayuda', category: 'Señales y símbolos', variations: [{ text: 'Ayuda', icon: 'mdi:help-circle' }], nouns: [], synonyms: [], antonyms: [] },
];
