const categoryData = {
    'Personas': { icon: 'mdi:account-group' },
    'Acciones': { icon: 'mdi:run' },
    'Preguntas': { icon: 'mdi:help-box' },
    'Pequeñas Palabras': { icon: 'mdi:format-letter-case' },
    'Comida': { icon: 'mdi:food-apple' },
    'Ropa': { icon: 'mdi:tshirt-crew' },
    'Animales': { icon: 'mdi:dog' },
    'Juguetes': { icon: 'mdi:toy-brick' },
    'Objetos': { icon: 'mdi:lightbulb' },
    'Lugares': { icon: 'mdi:home' },
    'Sentimientos': { icon: 'mdi:emoticon-happy' },
    'Conceptos': { icon: 'mdi:lightbulb-on' },
    'Tiempo': { icon: 'mdi:calendar-clock' },
    'Clima': { icon: 'mdi:weather-partly-cloudy' },
    'Colores': { icon: 'mdi:palette' },
    'Números': { icon: 'mdi:numeric' }
};

const pictogramData = [
    // Core: Personas y Pronombres
    { id: 'yo', category: 'Personas', variations: [{ text: 'Yo', icon: 'mdi:account' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'tu', category: 'Personas', variations: [{ text: 'Tú', icon: 'mdi:account-outline' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'el', category: 'Personas', variations: [{ text: 'Él', icon: 'mdi:gender-male' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'ella', category: 'Personas', variations: [{ text: 'Ella', icon: 'mdi:gender-female' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'nosotros', category: 'Personas', variations: [{ text: 'Nosotros', icon: 'mdi:account-group' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'ellos', category: 'Personas', variations: [{ text: 'Ellos', icon: 'mdi:account-multiple' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'mama', category: 'Personas', variations: [{ text: 'Mamá', icon: 'mdi:human-female-boy' }], nouns: ['madre'], synonyms: ['mamá', 'madre'], antonyms: [] },
    { id: 'papa', category: 'Personas', variations: [{ text: 'Papá', icon: 'mdi:human-male-girl' }], nouns: ['padre'], synonyms: ['papá', 'padre'], antonyms: [] },
    { id: 'bebe', category: 'Personas', variations: [{ text: 'Bebé', icon: 'mdi:baby-carriage' }], nouns: ['bebé', 'neonato'], synonyms: ['bebé', 'recién nacido'], antonyms: ['adulto'] },
    { id: 'nino', category: 'Personas', variations: [{ text: 'Niño', icon: 'mdi:human-child' }, { text: 'Niños', icon: 'mdi:human-male-male' }], nouns: ['niño', 'infante'], synonyms: ['chico', 'pequeño'], antonyms: ['adulto'] },
    { id: 'nina', category: 'Personas', variations: [{ text: 'Niña', icon: 'mdi:human-female-girl' }, { text: 'Niñas', icon: 'mdi:human-female-female' }], nouns: ['niña', 'infanta'], synonyms: ['chica', 'pequeña'], antonyms: ['adulta'] },
    { id: 'amigo', category: 'Personas', variations: [{ text: 'Amigo', icon: 'mdi:account-heart' }, { text: 'Amigos', icon: 'mdi:account-heart-outline' }], nouns: ['amistad', 'compañerismo'], synonyms: ['compañero', 'camarada'], antonyms: ['enemigo'] },
    { id: 'doctor', category: 'Personas', variations: [{ text: 'Doctor', icon: 'mdi:doctor' }], nouns: ['médico', 'doctor'], synonyms: ['galeno', 'facultativo'], antonyms: [] },
    { id: 'profesor', category: 'Personas', variations: [{ text: 'Profesor', icon: 'mdi:teach' }], nouns: ['maestro', 'docente'], synonyms: ['educador', 'instructor'], antonyms: ['alumno'] },

    // Core: Verbos / Acciones
    { id: 'quiero', category: 'Acciones', variations: [{ text: 'Quiero', icon: 'mdi:hand-pointing-right' }], nouns: ['deseo', 'voluntad'], synonyms: ['desear', 'anhelar'], antonyms: ['rechazar'] },
    { id: 'no_quiero', category: 'Acciones', variations: [{ text: 'No quiero', icon: 'mdi:hand-saw' }], nouns: ['rechazo', 'negativa'], synonyms: ['rechazar', 'negar'], antonyms: ['querer', 'desear'] },
    { id: 'comer', category: 'Acciones', variations: [{ text: 'Comer', icon: 'mdi:food-apple' }, { text: 'Comiendo', icon: 'mdi:food-apple-outline' }, { text: 'Comí', icon: 'mdi:food-apple' }], nouns: ['comida', 'alimento'], synonyms: ['alimentarse', 'ingerir'], antonyms: ['ayunar'] },
    { id: 'beber', category: 'Acciones', variations: [{ text: 'Beber', icon: 'mdi:cup-water' }, { text: 'Bebiendo', icon: 'mdi:cup' }, { text: 'Bebí', icon: 'mdi:cup-off' }], nouns: ['bebida'], synonyms: ['tomar', 'ingerir'], antonyms: [] },
    { id: 'jugar', category: 'Acciones', variations: [{ text: 'Jugar', icon: 'mdi:gamepad-variant' }, { text: 'Jugando', icon: 'mdi:gamepad' }, { text: 'Jugué', icon: 'mdi:gamepad-outline' }], nouns: ['juego', 'diversión'], synonyms: ['entretenerse', 'recrearse'], antonyms: ['trabajar', 'aburrirse'] },
    { id: 'ir', category: 'Acciones', variations: [{ text: 'Ir', icon: 'mdi:arrow-right-bold-circle' }, { text: 'Voy', icon: 'mdi:arrow-right-bold-circle-outline' }, { text: 'Fui', icon: 'mdi:arrow-right-bold' }], nouns: ['ida', 'partida'], synonyms: ['partir', 'dirigirse'], antonyms: ['venir', 'quedarse'] },
    { id: 'venir', category: 'Acciones', variations: [{ text: 'Venir', icon: 'mdi:arrow-left-bold-circle' }, { text: 'Vengo', icon: 'mdi:arrow-left-bold-circle-outline' }, { text: 'Vine', icon: 'mdi:arrow-left-bold' }], nouns: ['venida', 'llegada'], synonyms: ['llegar', 'acudir'], antonyms: ['ir', 'partir'] },
    { id: 'dormir', category: 'Acciones', variations: [{ text: 'Dormir', icon: 'mdi:sleep' }, { text: 'Durmiendo', icon: 'mdi:sleep-off' }, { text: 'Dormí', icon: 'mdi:bed' }], nouns: ['sueño', 'descanso'], synonyms: ['descansar', 'reposar'], antonyms: ['despertar'] },
    { id: 'despertar', category: 'Acciones', variations: [{ text: 'Despertar', icon: 'mdi:weather-sunny' }, { text: 'Despertando', icon: 'mdi:weather-sunny-alert' }, { text: 'Desperté', icon: 'mdi:weather-sunny-off' }], nouns: ['despertar'], synonyms: ['despabilar', 'activarse'], antonyms: ['dormir'] },
    { id: 'mirar', category: 'Acciones', variations: [{ text: 'Mirar', icon: 'mdi:eye' }, { text: 'Mirando', icon: 'mdi:eye-outline' }, { text: 'Miré', icon: 'mdi:eye-off' }], nouns: ['mirada', 'observación'], synonyms: ['observar', 'ver'], antonyms: ['ignorar'] },
    { id: 'escuchar', category: 'Acciones', variations: [{ text: 'Escuchar', icon: 'mdi:ear-hearing' }, { text: 'Escuchando', icon: 'mdi:ear-hearing-loop' }, { text: 'Escuché', icon: 'mdi:ear-hearing-off' }], nouns: ['escucha', 'audición'], synonyms: ['oír', 'atender'], antonyms: ['ignorar'] },
    { id: 'hablar', category: 'Acciones', variations: [{ text: 'Hablar', icon: 'mdi:message-text' }, { text: 'Hablando', icon: 'mdi:message-text-outline' }, { text: 'Hablé', icon: 'mdi:message' }], nouns: ['habla', 'conversación'], synonyms: ['conversar', 'dialogar'], antonyms: ['callar'] },
    { id: 'cantar', category: 'Acciones', variations: [{ text: 'Cantar', icon: 'mdi:microphone-variant' }, { text: 'Cantando', icon: 'mdi:microphone' }, { text: 'Canté', icon: 'mdi:microphone-off' }], nouns: ['canto', 'canción'], synonyms: ['entonar', 'vocalizar'], antonyms: [] },
    { id: 'bailar', category: 'Acciones', variations: [{ text: 'Bailar', icon: 'mdi:dance-ballroom' }, { text: 'Bailando', icon: 'mdi:human-female-dance' }, { text: 'Bailé', icon: 'mdi:human-male-dance' }], nouns: ['baile', 'danza'], synonyms: ['danzar', 'moverse'], antonyms: [] },
    { id: 'leer', category: 'Acciones', variations: [{ text: 'Leer', icon: 'mdi:book-open-page-variant' }, { text: 'Leyendo', icon: 'mdi:book-open' }, { text: 'Leí', icon: 'mdi:book' }], nouns: ['lectura', 'libro'], synonyms: ['interpretar', 'descifrar'], antonyms: ['escribir'] },
    { id: 'escribir', category: 'Acciones', variations: [{ text: 'Escribir', icon: 'mdi:pencil' }, { text: 'Escribiendo', icon: 'mdi:pencil-outline' }, { text: 'Escribí', icon: 'mdi:pencil-off' }], nouns: ['escritura', 'texto'], synonyms: ['redactar', 'anotar'], antonyms: ['leer'] },
    { id: 'pintar', category: 'Acciones', variations: [{ text: 'Pintar', icon: 'mdi:palette' }, { text: 'Pintando', icon: 'mdi:palette-outline' }, { text: 'Pinté', icon: 'mdi:palette-swatch' }], nouns: ['pintura', 'dibujo'], synonyms: ['dibujar', 'colorear'], antonyms: [] },
    { id: 'correr', category: 'Acciones', variations: [{ text: 'Correr', icon: 'mdi:run' }, { text: 'Corriendo', icon: 'mdi:run-fast' }, { text: 'Corrí', icon: 'mdi:walk' }], nouns: ['carrera'], synonyms: ['trotar', 'galopar'], antonyms: ['caminar', 'detenerse'] },
    { id: 'caminar', category: 'Acciones', variations: [{ text: 'Caminar', icon: 'mdi:walk' }, { text: 'Caminando', icon: 'mdi:human-male-female' }, { text: 'Caminé', icon: 'mdi:foot-print' }], nouns: ['caminata', 'paseo'], synonyms: ['andar', 'pasear'], antonyms: ['correr', 'detenerse'] },
    { id: 'saltar', category: 'Acciones', variations: [{ text: 'Saltar', icon: 'mdi:jump-rope' }, { text: 'Saltando', icon: 'mdi:rabbit' }, { text: 'Salté', icon: 'mdi:human-jump' }], nouns: ['salto', 'brinco'], synonyms: ['brincar', 'botar'], antonyms: [] },
    { id: 'sentarse', category: 'Acciones', variations: [{ text: 'Sentarse', icon: 'mdi:seat' }, { text: 'Sentado', icon: 'mdi:seat-outline' }, { text: 'Me senté', icon: 'mdi:seat-recline' }], nouns: [], synonyms: ['tomar asiento'], antonyms: ['levantarse'] },
    { id: 'levantarse', category: 'Acciones', variations: [{ text: 'Levantarse', icon: 'mdi:human-male-height' }, { text: 'Levantado', icon: 'mdi:human-male-height-variant' }, { text: 'Me levanté', icon: 'mdi:human-handsup' }], nouns: [], synonyms: ['ponerse de pie'], antonyms: ['sentarse'] },
    { id: 'abrir', category: 'Acciones', variations: [{ text: 'Abrir', icon: 'mdi:door-open' }, { text: 'Abriendo', icon: 'mdi:door' }, { text: 'Abrí', icon: 'mdi:door-sliding' }], nouns: ['apertura'], synonyms: ['destapar', 'descubrir'], antonyms: ['cerrar'] },
    { id: 'cerrar', category: 'Acciones', variations: [{ text: 'Cerrar', icon: 'mdi:door-closed' }, { text: 'Cerrando', icon: 'mdi:door-closed-lock' }, { text: 'Cerré', icon: 'mdi:door-sliding-lock' }], nouns: ['cierre'], synonyms: ['tapar', 'sellar'], antonyms: ['abrir'] },
    { id: 'dar', category: 'Acciones', variations: [{ text: 'Dar', icon: 'mdi:gift' }, { text: 'Dando', icon: 'mdi:gift-outline' }, { text: 'Di', icon: 'mdi:gift-open' }], nouns: ['entrega', 'regalo'], synonyms: ['entregar', 'ofrecer'], antonyms: ['recibir'] },
    { id: 'recibir', category: 'Acciones', variations: [{ text: 'Recibir', icon: 'mdi:download' }, { text: 'Recibiendo', icon: 'mdi:download-outline' }, { text: 'Recibí', icon: 'mdi:download-off' }], nouns: ['recepción'], synonyms: ['aceptar', 'tomar'], antonyms: ['dar'] },
    { id: 'ayudar', category: 'Acciones', variations: [{ text: 'Ayudar', icon: 'mdi:help-circle' }, { text: 'Ayudando', icon: 'mdi:help-circle-outline' }, { text: 'Ayudé', icon: 'mdi:help' }], nouns: ['ayuda', 'asistencia'], synonyms: ['asistir', 'colaborar'], antonyms: ['obstaculizar'] },
    { id: 'trabajar', category: 'Acciones', variations: [{ text: 'Trabajar', icon: 'mdi:briefcase' }, { text: 'Trabajando', icon: 'mdi:briefcase-outline' }, { text: 'Trabajé', icon: 'mdi:briefcase-off' }], nouns: ['trabajo', 'empleo'], synonyms: ['laborar', 'operar'], antonyms: ['descansar'] },
    { id: 'estudiar', category: 'Acciones', variations: [{ text: 'Estudiar', icon: 'mdi:school' }, { text: 'Estudiando', icon: 'mdi:school-outline' }, { text: 'Estudié', icon: 'mdi:book-open-variant' }], nouns: ['estudio', 'aprendizaje'], synonyms: ['aprender', 'investigar'], antonyms: [] },
    { id: 'lavar', category: 'Acciones', variations: [{ text: 'Lavar', icon: 'mdi:water' }, { text: 'Lavando', icon: 'mdi:water-outline' }, { text: 'Lavé', icon: 'mdi:water-off' }], nouns: ['lavado', 'limpieza'], synonyms: ['limpiar', 'asear'], antonyms: ['ensuciar'] },
    { id: 'banarse', category: 'Acciones', variations: [{ text: 'Bañarse', icon: 'mdi:shower-head' }, { text: 'Bañando', icon: 'mdi:shower' }, { text: 'Me bañé', icon: 'mdi:hot-tub' }], nouns: ['baño', 'aseo'], synonyms: ['ducharse', 'asearse'], antonyms: [] },
    { id: 'vestirse', category: 'Acciones', variations: [{ text: 'Vestirse', icon: 'mdi:tshirt-crew' }, { text: 'Vistiendo', icon: 'mdi:tshirt-crew-outline' }, { text: 'Me vestí', icon: 'mdi:human-female-dress' }], nouns: ['vestimenta', 'ropa'], synonyms: ['ataviarse', 'ponerse'], antonyms: ['desnudarse'] },
    { id: 'peinarse', category: 'Acciones', variations: [{ text: 'Peinarse', icon: 'mdi:hair-dryer' }, { text: 'Peinando', icon: 'mdi:hair-dryer-outline' }, { text: 'Me peiné', icon: 'mdi:face-woman-shimmer' }], nouns: ['peinado'], synonyms: ['arreglarse el pelo'], antonyms: ['despeinarse'] },
    { id: 'cepillarse', category: 'Acciones', variations: [{ text: 'Cepillarse', icon: 'mdi:brush' }, { text: 'Cepillando', icon: 'mdi:brush-outline' }, { text: 'Me cepillé', icon: 'mdi:tooth' }], nouns: ['cepillado'], synonyms: ['limpiarse'], antonyms: [] },

    // Core: Preguntas
    { id: 'que', category: 'Preguntas', variations: [{ text: 'Qué', icon: 'mdi:help-box' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'quien', category: 'Preguntas', variations: [{ text: 'Quién', icon: 'mdi:account-question' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'cuando', category: 'Preguntas', variations: [{ text: 'Cuándo', icon: 'mdi:calendar-question' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'donde', category: 'Preguntas', variations: [{ text: 'Dónde', icon: 'mdi:map-marker-question' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'porque', category: 'Preguntas', variations: [{ text: 'Porqué', icon: 'mdi:comment-question' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'como', category: 'Preguntas', variations: [{ text: 'Cómo', icon: 'mdi:information' }], nouns: [], synonyms: [], antonyms: [] },

    // Core: Pequeñas Palabras
    { id: 'y', category: 'Pequeñas Palabras', variations: [{ text: 'Y', icon: 'mdi:plus' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'con', category: 'Pequeñas Palabras', variations: [{ text: 'Con', icon: 'mdi:link' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'el', category: 'Pequeñas Palabras', variations: [{ text: 'El', icon: 'mdi:alpha-e-box' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'la', category: 'Pequeñas Palabras', variations: [{ text: 'La', icon: 'mdi:alpha-l-box' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'en', category: 'Pequeñas Palabras', variations: [{ text: 'En', icon: 'mdi:alpha-e-box-outline' }], nouns: [], synonyms: [], antonyms: [] },
    { id: 'pero', category: 'Pequeñas Palabras', variations: [{ text: 'Pero', icon: 'mdi:alpha-p-box' }], nouns: [], synonyms: [], antonyms: [] },

    // Fringe: Comida
    { id: 'agua', category: 'Comida', variations: [{ text: 'Agua', icon: 'mdi:cup' }], nouns: ['agua', 'líquido'], synonyms: ['líquido'], antonyms: [] },
    { id: 'leche', category: 'Comida', variations: [{ text: 'Leche', icon: 'mdi:cup-off' }], nouns: ['leche', 'lácteo'], synonyms: [], antonyms: [] },
    { id: 'jugo', category: 'Comida', variations: [{ text: 'Jugo', icon: 'mdi:food-fork-drink' }], nouns: ['jugo', 'zumo'], synonyms: ['zumo'], antonyms: [] },
    { id: 'pan', category: 'Comida', variations: [{ text: 'Pan', icon: 'mdi:bread-slice' }], nouns: ['pan'], synonyms: [], antonyms: [] },
    { id: 'manzana', category: 'Comida', variations: [{ text: 'Manzana', icon: 'mdi:food-apple-outline' }, { text: 'Manzanas', icon: 'mdi:food-apple' }], nouns: ['manzana', 'fruta'], synonyms: [], antonyms: [] },
    { id: 'platano', category: 'Comida', variations: [{ text: 'Plátano', icon: 'mdi:food-banana' }], nouns: ['plátano', 'banana', 'fruta'], synonyms: ['banana'], antonyms: [] },
    { id: 'naranja', category: 'Comida', variations: [{ text: 'Naranja', icon: 'mdi:food-orange' }], nouns: ['naranja', 'fruta'], synonyms: [], antonyms: [] },
    { id: 'fresa', category: 'Comida', variations: [{ text: 'Fresa', icon: 'mdi:food-strawberry' }], nouns: ['fresa', 'fruta'], synonyms: [], antonyms: [] },
    { id: 'galleta', category: 'Comida', variations: [{ text: 'Galleta', icon: 'mdi:cookie' }, { text: 'Galletas', icon: 'mdi:cookie-outline' }], nouns: ['galleta', 'bizcocho'], synonyms: ['bizcocho'], antonyms: [] },
    { id: 'queso', category: 'Comida', variations: [{ text: 'Queso', icon: 'mdi:cheese' }], nouns: ['queso', 'lácteo'], synonyms: [], antonyms: [] },
    { id: 'huevo', category: 'Comida', variations: [{ text: 'Huevo', icon: 'mdi:egg-easter' }, { text: 'Huevos', icon: 'mdi:egg' }], nouns: ['huevo'], synonyms: [], antonyms: [] },
    { id: 'pollo', category: 'Comida', variations: [{ text: 'Pollo', icon: 'mdi:food-drumstick' }], nouns: ['pollo', 'carne'], synonyms: [], antonyms: [] },
    { id: 'carne', category: 'Comida', variations: [{ text: 'Carne', icon: 'mdi:food-steak' }], nouns: ['carne', 'filete'], synonyms: ['filete'], antonyms: [] },
    { id: 'pescado', category: 'Comida', variations: [{ text: 'Pescado', icon: 'mdi:fish' }], nouns: ['pescado', 'pez'], synonyms: [], antonyms: [] },
    { id: 'arroz', category: 'Comida', variations: [{ text: 'Arroz', icon: 'mdi:rice' }], nouns: ['arroz', 'cereal'], synonyms: [], antonyms: [] },
    { id: 'pasta', category: 'Comida', variations: [{ text: 'Pasta', icon: 'mdi:food-croissant' }], nouns: ['pasta'], synonyms: [], antonyms: [] },
    { id: 'sopa', category: 'Comida', variations: [{ text: 'Sopa', icon: 'mdi:bowl-mix' }], nouns: ['sopa', 'caldo'], synonyms: ['caldo'], antonyms: [] },
    { id: 'ensalada', category: 'Comida', variations: [{ text: 'Ensalada', icon: 'mdi:leaf' }], nouns: ['ensalada', 'verdura'], synonyms: [], antonyms: [] },
    { id: 'helado', category: 'Comida', variations: [{ text: 'Helado', icon: 'mdi:ice-cream' }], nouns: ['helado', 'postre'], synonyms: [], antonyms: [] },
    { id: 'torta', category: 'Comida', variations: [{ text: 'Torta', icon: 'mdi:cake-variant' }], nouns: ['torta', 'pastel', 'postre'], synonyms: ['pastel'], antonyms: [] },
    { id: 'desayuno', category: 'Comida', variations: [{ text: 'Desayuno', icon: 'mdi:weather-sunset-up' }], nouns: ['desayuno', 'comida'], synonyms: [], antonyms: ['cena'] },
    { id: 'almuerzo', category: 'Comida', variations: [{ text: 'Almuerzo', icon: 'mdi:weather-sunny' }], nouns: ['almuerzo', 'comida'], synonyms: [], antonyms: ['desayuno', 'cena'] },
    { id: 'cena', category: 'Comida', variations: [{ text: 'Cena', icon: 'mdi:weather-night' }], nouns: ['cena', 'comida'], synonyms: [], antonyms: ['desayuno'] },

    // Fringe: Ropa
    { id: 'camiseta', category: 'Ropa', variations: [{ text: 'Camiseta', icon: 'mdi:tshirt-v' }], nouns: ['camiseta', 'prenda'], synonyms: ['playera', 'remera'], antonyms: [] },
    { id: 'pantalon', category: 'Ropa', variations: [{ text: 'Pantalón', icon: 'mdi:pants' }], nouns: ['pantalón', 'prenda'], synonyms: [], antonyms: [] },
    { id: 'vestido', category: 'Ropa', variations: [{ text: 'Vestido', icon: 'mdi:human-female-dress' }], nouns: ['vestido', 'prenda'], synonyms: [], antonyms: [] },
    { id: 'falda', category: 'Ropa', variations: [{ text: 'Falda', icon: 'mdi:skirt' }], nouns: ['falda', 'prenda'], synonyms: [], antonyms: [] },
    { id: 'zapatos', category: 'Ropa', variations: [{ text: 'Zapatos', icon: 'mdi:shoe-sneaker' }], nouns: ['zapato', 'calzado'], synonyms: ['calzado'], antonyms: [] },
    { id: 'medias', category: 'Ropa', variations: [{ text: 'Medias', icon: 'mdi:socks' }], nouns: ['media', 'calcetín'], synonyms: ['calcetines'], antonyms: [] },
    { id: 'abrigo', category: 'Ropa', variations: [{ text: 'Abrigo', icon: 'mdi:jacket' }], nouns: ['abrigo', 'chaqueta'], synonyms: ['chaqueta', 'cazadora'], antonyms: [] },
    { id: 'sombrero', category: 'Ropa', variations: [{ text: 'Sombrero', icon: 'mdi:hat-fedora' }], nouns: ['sombrero', 'gorro'], synonyms: ['gorro'], antonyms: [] },
    { id: 'gafas', category: 'Ropa', variations: [{ text: 'Gafas', icon: 'mdi:glasses' }], nouns: ['gafas', 'lentes'], synonyms: ['lentes', 'anteojos'], antonyms: [] },

    // Fringe: Animales
    { id: 'perro', category: 'Animales', variations: [{ text: 'Perro', icon: 'mdi:dog' }, { text: 'Perros', icon: 'mdi:dog-side' }], nouns: ['perro', 'can'], synonyms: ['can'], antonyms: [] },
    { id: 'gato', category: 'Animales', variations: [{ text: 'Gato', icon: 'mdi:cat' }, { text: 'Gatos', icon: 'mdi:cat-off' }], nouns: ['gato', 'felino'], synonyms: ['felino'], antonyms: [] },
    { id: 'pajaro', category: 'Animales', variations: [{ text: 'Pájaro', icon: 'mdi:bird' }], nouns: ['pájaro', 'ave'], synonyms: ['ave'], antonyms: [] },
    { id: 'pez', category: 'Animales', variations: [{ text: 'Pez', icon: 'mdi:fish' }, { text: 'Peces', icon: 'mdi:fish-off' }], nouns: ['pez', 'pescado'], synonyms: [], antonyms: [] },
    { id: 'conejo', category: 'Animales', variations: [{ text: 'Conejo', icon: 'mdi:rabbit' }], nouns: ['conejo'], synonyms: [], antonyms: [] },
    { id: 'caballo', category: 'Animales', variations: [{ text: 'Caballo', icon: 'mdi:horse' }], nouns: ['caballo', 'equino'], synonyms: ['equino'], antonyms: [] },
    { id: 'vaca', category: 'Animales', variations: [{ text: 'Vaca', icon: 'mdi:cow' }], nouns: ['vaca', 'bovino'], synonyms: [], antonyms: [] },
    { id: 'cerdo', category: 'Animales', variations: [{ text: 'Cerdo', icon: 'mdi:pig' }], nouns: ['cerdo', 'puerco'], synonyms: ['puerco', 'cochino'], antonyms: [] },
    { id: 'oveja', category: 'Animales', variations: [{ text: 'Oveja', icon: 'mdi:sheep' }], nouns: ['oveja', 'ovino'], synonyms: [], antonyms: [] },
    { id: 'leon', category: 'Animales', variations: [{ text: 'León', icon: 'mdi:lion' }], nouns: ['león', 'felino'], synonyms: [], antonyms: [] },
    { id: 'tigre', category: 'Animales', variations: [{ text: 'Tigre', icon: 'mdi:tiger' }], nouns: ['tigre', 'felino'], synonyms: [], antonyms: [] },
    { id: 'elefante', category: 'Animales', variations: [{ text: 'Elefante', icon: 'mdi:elephant' }], nouns: ['elefante'], synonyms: [], antonyms: [] },
    { id: 'mono', category: 'Animales', variations: [{ text: 'Mono', icon: 'mdi:monkey' }], nouns: ['mono', 'primate'], synonyms: ['simio'], antonyms: [] },
    { id: 'serpiente', category: 'Animales', variations: [{ text: 'Serpiente', icon: 'mdi:snake' }], nouns: ['serpiente', 'reptil'], synonyms: ['culebra'], antonyms: [] },
    { id: 'mariposa', category: 'Animales', variations: [{ text: 'Mariposa', icon: 'mdi:butterfly' }], nouns: ['mariposa', 'insecto'], synonyms: [], antonyms: [] },

    // Fringe: Juguetes y Objetos
    { id: 'pelota', category: 'Juguetes', variations: [{ text: 'Pelota', icon: 'mdi:soccer' }], nouns: ['pelota', 'balón'], synonyms: ['balón'], antonyms: [] },
    { id: 'muneca', category: 'Juguetes', variations: [{ text: 'Muñeca', icon: 'mdi:human-female' }], nouns: ['muñeca', 'juguete'], synonyms: [], antonyms: [] },
    { id: 'carro', category: 'Juguetes', variations: [{ text: 'Carro', icon: 'mdi:car' }], nouns: ['carro', 'coche', 'automóvil'], synonyms: ['coche', 'automóvil'], antonyms: [] },
    { id: 'tren', category: 'Juguetes', variations: [{ text: 'Tren', icon: 'mdi:train' }], nouns: ['tren', 'ferrocarril'], synonyms: ['ferrocarril'], antonyms: [] },
    { id: 'avion', category: 'Juguetes', variations: [{ text: 'Avión', icon: 'mdi:airplane' }], nouns: ['avión', 'aeroplano'], synonyms: ['aeroplano'], antonyms: [] },
    { id: 'barco', category: 'Juguetes', variations: [{ text: 'Barco', icon: 'mdi:boat' }], nouns: ['barco', 'navío'], synonyms: ['navío', 'embarcación'], antonyms: [] },
    { id: 'bloques', category: 'Juguetes', variations: [{ text: 'Bloques', icon: 'mdi:toy-brick' }], nouns: ['bloque', 'juguete'], synonyms: [], antonyms: [] },
    { id: 'libro', category: 'Juguetes', variations: [{ text: 'Libro', icon: 'mdi:book' }], nouns: ['libro', 'obra'], synonyms: [], antonyms: [] },
    { id: 'lapiz', category: 'Juguetes', variations: [{ text: 'Lápiz', icon: 'mdi:pencil-box' }], nouns: ['lápiz', 'utensilio'], synonyms: [], antonyms: [] },
    { id: 'crayola', category: 'Juguetes', variations: [{ text: 'Crayola', icon: 'mdi:pen' }], nouns: ['crayola', 'cera'], synonyms: ['cera'], antonyms: [] },
    { id: 'tijeras', category: 'Juguetes', variations: [{ text: 'Tijeras', icon: 'mdi:content-cut' }], nouns: ['tijeras', 'herramienta'], synonyms: [], antonyms: [] },
    { id: 'pega', category: 'Juguetes', variations: [{ text: 'Pega', icon: 'mdi:glue-stick' }], nouns: ['pega', 'pegamento'], synonyms: ['pegamento', 'cola'], antonyms: [] },
    { id: 'mesa', category: 'Objetos', variations: [{ text: 'Mesa', icon: 'mdi:table-furniture' }], nouns: ['mesa', 'mueble'], synonyms: [], antonyms: [] },
    { id: 'silla', category: 'Objetos', variations: [{ text: 'Silla', icon: 'mdi:chair-rolling' }], nouns: ['silla', 'asiento'], synonyms: ['asiento'], antonyms: [] },
    { id: 'cama', category: 'Objetos', variations: [{ text: 'Cama', icon: 'mdi:bed' }], nouns: ['cama', 'lecho'], synonyms: ['lecho'], antonyms: [] },
    { id: 'puerta', category: 'Objetos', variations: [{ text: 'Puerta', icon: 'mdi:door' }], nouns: ['puerta', 'entrada'], synonyms: ['entrada', 'acceso'], antonyms: [] },
    { id: 'ventana', category: 'Objetos', variations: [{ text: 'Ventana', icon: 'mdi:window-maximize' }], nouns: ['ventana', 'abertura'], synonyms: [], antonyms: [] },
    { id: 'luz', category: 'Objetos', variations: [{ text: 'Luz', icon: 'mdi:lightbulb' }], nouns: ['luz', 'iluminación'], synonyms: ['iluminación', 'claridad'], antonyms: ['oscuridad'] },
    { id: 'telefono', category: 'Objetos', variations: [{ text: 'Teléfono', icon: 'mdi:phone' }], nouns: ['teléfono', 'aparato'], synonyms: [], antonyms: [] },
    { id: 'television', category: 'Objetos', variations: [{ text: 'Televisión', icon: 'mdi:television' }], nouns: ['televisión', 'televisor'], synonyms: ['televisor'], antonyms: [] },
    { id: 'computadora', category: 'Objetos', variations: [{ text: 'Computadora', icon: 'mdi:laptop' }], nouns: ['computadora', 'ordenador'], synonyms: ['ordenador'], antonyms: [] },
    { id: 'reloj', category: 'Objetos', variations: [{ text: 'Reloj', icon: 'mdi:clock' }], nouns: ['reloj', 'cronómetro'], synonyms: [], antonyms: [] },

    // Fringe: Lugares
    { id: 'casa', category: 'Lugares', variations: [{ text: 'Casa', icon: 'mdi:home' }], nouns: ['casa', 'hogar', 'vivienda'], synonyms: ['hogar', 'vivienda', 'domicilio'], antonyms: [] },
    { id: 'escuela', category: 'Lugares', variations: [{ text: 'Escuela', icon: 'mdi:school' }], nouns: ['escuela', 'colegio'], synonyms: ['colegio', 'instituto'], antonyms: [] },
    { id: 'parque', category: 'Lugares', variations: [{ text: 'Parque', icon: 'mdi:pine-tree' }], nouns: ['parque', 'jardín'], synonyms: ['jardín'], antonyms: [] },
    { id: 'tienda', category: 'Lugares', variations: [{ text: 'Tienda', icon: 'mdi:store' }], nouns: ['tienda', 'comercio'], synonyms: ['comercio', 'negocio'], antonyms: [] },
    { id: 'hospital', category: 'Lugares', variations: [{ text: 'Hospital', icon: 'mdi:hospital-building' }], nouns: ['hospital', 'clínica'], synonyms: ['clínica', 'sanatorio'], antonyms: [] },
    { id: 'playa', category: 'Lugares', variations: [{ text: 'Playa', icon: 'mdi:beach' }], nouns: ['playa', 'costa'], synonyms: ['costa'], antonyms: [] },
    { id: 'piscina', category: 'Lugares', variations: [{ text: 'Piscina', icon: 'mdi:pool' }], nouns: ['piscina', 'alberca'], synonyms: ['alberca'], antonyms: [] },
    { id: 'cine', category: 'Lugares', variations: [{ text: 'Cine', icon: 'mdi:movie' }], nouns: ['cine', 'sala de cine'], synonyms: [], antonyms: [] },
    { id: 'restaurante', category: 'Lugares', variations: [{ text: 'Restaurante', icon: 'mdi:restaurant' }], nouns: ['restaurante', 'comedor'], synonyms: [], antonyms: [] },
    { id: 'bano', category: 'Lugares', variations: [{ text: 'Baño', icon: 'mdi:toilet' }], nouns: ['baño', 'aseo'], synonyms: ['aseo', 'servicio'], antonyms: [] },
    { id: 'cocina', category: 'Lugares', variations: [{ text: 'Cocina', icon: 'mdi:pot-steam' }], nouns: ['cocina'], synonyms: [], antonyms: [] },
    { id: 'dormitorio', category: 'Lugares', variations: [{ text: 'Dormitorio', icon: 'mdi:bed-king' }], nouns: ['dormitorio', 'habitación', 'cuarto'], synonyms: ['habitación', 'cuarto', 'alcoba'], antonyms: [] },
    { id: 'sala', category: 'Lugares', variations: [{ text: 'Sala', icon: 'mdi:sofa' }], nouns: ['sala', 'salón'], synonyms: ['salón', 'living'], antonyms: [] },
    { id: 'jardin', category: 'Lugares', variations: [{ text: 'Jardín', icon: 'mdi:flower' }], nouns: ['jardín', 'patio'], synonyms: ['patio'], antonyms: [] },

    // Fringe: Emociones y Adjetivos
    { id: 'feliz', category: 'Sentimientos', variations: [{ text: 'Feliz', icon: 'mdi:emoticon-happy' }, { text: 'Felices', icon: 'mdi:emoticon-happy-outline' }], nouns: ['felicidad', 'alegría', 'contento'], synonyms: ['alegre', 'contento', 'dichoso', 'satisfecho'], antonyms: ['triste', 'infeliz', 'desdichado'] },
    { id: 'triste', category: 'Sentimientos', variations: [{ text: 'Triste', icon: 'mdi:emoticon-sad' }, { text: 'Tristes', icon: 'mdi:emoticon-sad-outline' }], nouns: ['tristeza', 'pena', 'desdicha'], synonyms: ['apenado', 'melancólico', 'desconsolado'], antonyms: ['feliz', 'alegre', 'contento'] },
    { id: 'enojado', category: 'Sentimientos', variations: [{ text: 'Enojado', icon: 'mdi:emoticon-angry' }, { text: 'Enojados', icon: 'mdi:emoticon-angry-outline' }], nouns: ['enojo', 'ira', 'furia'], synonyms: ['enfadado', 'molesto', 'furioso'], antonyms: ['contento', 'calmado'] },
    { id: 'asustado', category: 'Sentimientos', variations: [{ text: 'Asustado', icon: 'mdi:emoticon-dead' }, { text: 'Asustados', icon: 'mdi:emoticon-dead-outline' }], nouns: ['susto', 'miedo', 'temor'], synonyms: ['atemorizado', 'espantado'], antonyms: ['valiente', 'tranquilo'] },
    { id: 'sorprendido', category: 'Sentimientos', variations: [{ text: 'Sorprendido', icon: 'mdi:emoticon-excited' }, { text: 'Sorprendidos', icon: 'mdi:emoticon-excited-outline' }], nouns: ['sorpresa', 'asombro'], synonyms: ['asombrado', 'pasmado'], antonyms: [] },
    { id: 'cansado', category: 'Sentimientos', variations: [{ text: 'Cansado', icon: 'mdi:battery-30' }, { text: 'Cansados', icon: 'mdi:battery-10' }], nouns: ['cansancio', 'fatiga'], synonyms: ['fatigado', 'agotado'], antonyms: ['descansado', 'enérgico'] },
    { id: 'enfermo', category: 'Sentimientos', variations: [{ text: 'Enfermo', icon: 'mdi:emoticon-sick' }, { text: 'Enfermos', icon: 'mdi:emoticon-sick-outline' }], nouns: ['enfermedad', 'padecimiento'], synonyms: ['indispuesto', 'achacoso'], antonyms: ['sano', 'saludable'] },
    { id: 'bien', category: 'Sentimientos', variations: [{ text: 'Bien', icon: 'mdi:thumb-up' }], nouns: ['bienestar'], synonyms: ['correcto', 'adecuado'], antonyms: ['mal'] },
    { id: 'mal', category: 'Sentimientos', variations: [{ text: 'Mal', icon: 'mdi:thumb-down' }], nouns: ['malestar'], synonyms: ['incorrecto', 'inadecuado'], antonyms: ['bien'] },
    { id: 'frustrado', category: 'Sentimientos', variations: [{ text: 'Frustrado', icon: 'mdi:emoticon-confused' }], nouns: ['frustración', 'decepción'], synonyms: ['decepcionado', 'desilusionado'], antonyms: ['satisfecho', 'realizado'] },
    { id: 'emocionado', category: 'Sentimientos', variations: [{ text: 'Emocionado', icon: 'mdi:emoticon-cool' }], nouns: ['emoción', 'entusiasmo'], synonyms: ['entusiasmado', 'conmovido'], antonyms: ['indiferente'] },
    { id: 'timido', category: 'Sentimientos', variations: [{ text: 'Tímido', icon: 'mdi:emoticon-neutral' }], nouns: ['timidez', 'vergüenza'], synonyms: ['vergonzoso', 'retraído'], antonyms: ['extrovertido', 'sociable'] },
    { id: 'grande', category: 'Conceptos', variations: [{ text: 'Grande', icon: 'mdi:arrow-expand-all' }, { text: 'Grandes', icon: 'mdi:arrow-expand' }], nouns: ['tamaño', 'magnitud', 'extensión'], synonyms: ['enorme', 'inmenso', 'colosal'], antonyms: ['pequeño', 'diminuto', 'insignificante'] },
    { id: 'pequeno', category: 'Conceptos', variations: [{ text: 'Pequeño', icon: 'mdi:arrow-collapse-all' }, { text: 'Pequeños', icon: 'mdi:arrow-collapse' }], nouns: ['tamaño', 'miniatura'], synonyms: ['diminuto', 'menudo', 'chico'], antonyms: ['grande', 'enorme'] },
    { id: 'caliente', category: 'Conceptos', variations: [{ text: 'Caliente', icon: 'mdi:fire' }], nouns: ['calor', 'temperatura'], synonyms: ['cálido', 'caluroso'], antonyms: ['frío'] },
    { id: 'frio', category: 'Conceptos', variations: [{ text: 'Frío', icon: 'mdi:snowflake' }], nouns: ['frío', 'temperatura'], synonyms: ['helado', 'gélido'], antonyms: ['caliente'] },
    { id: 'rapido', category: 'Conceptos', variations: [{ text: 'Rápido', icon: 'mdi:run-fast' }], nouns: ['velocidad', 'rapidez'], synonyms: ['veloz', 'ligero'], antonyms: ['lento'] },
    { id: 'lento', category: 'Conceptos', variations: [{ text: 'Lento', icon: 'mdi:tortoise' }], nouns: ['lentitud', 'calma'], synonyms: ['pausado', 'tranquilo'], antonyms: ['rápido'] },
    { id: 'bonito', category: 'Conceptos', variations: [{ text: 'Bonito', icon: 'mdi:heart' }, { text: 'Bonitos', icon: 'mdi:heart-multiple' }], nouns: ['belleza', 'hermosura'], synonyms: ['hermoso', 'bello', 'lindo'], antonyms: ['feo'] },
    { id: 'feo', category: 'Conceptos', variations: [{ text: 'Feo', icon: 'mdi:heart-broken' }, { text: 'Feos', icon: 'mdi:heart-broken-outline' }], nouns: ['fealdad'], synonyms: ['desagradable', 'horrible'], antonyms: ['bonito', 'hermoso'] },
    { id: 'limpio', category: 'Conceptos', variations: [{ text: 'Limpio', icon: 'mdi:clean' }], nouns: ['limpieza', 'aseo'], synonyms: ['aseado', 'higiénico'], antonyms: ['sucio'] },
    { id: 'sucio', category: 'Conceptos', variations: [{ text: 'Sucio', icon: 'mdi:dirty' }], nouns: ['suciedad', 'mancha'], synonyms: ['manchado', 'mugriento'], antonyms: ['limpio'] },
    { id: 'fuerte', category: 'Conceptos', variations: [{ text: 'Fuerte', icon: 'mdi:arm-flex' }], nouns: ['fuerza', 'potencia'], synonyms: ['robusto', 'vigoroso'], antonyms: ['débil'] },
    { id: 'debil', category: 'Conceptos', variations: [{ text: 'Débil', icon: 'mdi:arm-flex-outline' }], nouns: ['debilidad', 'fragilidad'], synonyms: ['frágil', 'endeble'], antonyms: ['fuerte'] },

    // Fringe: Tiempo y Clima
    { id: 'hoy', category: 'Tiempo', variations: [{ text: 'Hoy', icon: 'mdi:calendar-today' }], nouns: ['presente'], synonyms: ['actualmente'], antonyms: ['ayer', 'mañana'] },
    { id: 'ayer', category: 'Tiempo', variations: [{ text: 'Ayer', icon: 'mdi:calendar-arrow-left' }], nouns: ['pasado'], synonyms: ['antier'], antonyms: ['hoy', 'mañana'] },
    { id: 'manana', category: 'Tiempo', variations: [{ text: 'Mañana', icon: 'mdi:calendar-arrow-right' }], nouns: ['futuro'], synonyms: ['pasado mañana'], antonyms: ['hoy', 'ayer'] },
    { id: 'ahora', category: 'Tiempo', variations: [{ text: 'Ahora', icon: 'mdi:clock-time-eight' }], nouns: ['presente', 'momento'], synonyms: ['ya', 'en este momento'], antonyms: ['antes', 'después'] },
    { id: 'despues', category: 'Tiempo', variations: [{ text: 'Después', icon: 'mdi:arrow-right' }], nouns: [], synonyms: ['luego', 'más tarde'], antonyms: ['antes'] },
    { id: 'antes', category: 'Tiempo', variations: [{ text: 'Antes', icon: 'mdi:arrow-left' }], nouns: [], synonyms: ['previamente', 'anteriormente'], antonyms: ['después'] },
    { id: 'dia', category: 'Tiempo', variations: [{ text: 'Día', icon: 'mdi:weather-sunny' }], nouns: ['día', 'jornada'], synonyms: ['jornada'], antonyms: ['noche'] },
    { id: 'noche', category: 'Tiempo', variations: [{ text: 'Noche', icon: 'mdi:weather-night' }], nouns: ['noche', 'oscuridad'], synonyms: [], antonyms: ['día'] },
    { id: 'sol', category: 'Clima', variations: [{ text: 'Sol', icon: 'mdi:white-balance-sunny' }], nouns: ['sol', 'estrella'], synonyms: [], antonyms: [] },
    { id: 'lluvia', category: 'Clima', variations: [{ text: 'Lluvia', icon: 'mdi:weather-rainy' }], nouns: ['lluvia', 'precipitación'], synonyms: ['precipitación', 'aguacero'], antonyms: ['sequía'] },
    { id: 'nube', category: 'Clima', variations: [{ text: 'Nube', icon: 'mdi:weather-cloudy' }], nouns: ['nube'], synonyms: [], antonyms: [] },
    { id: 'viento', category: 'Clima', variations: [{ text: 'Viento', icon: 'mdi:weather-windy' }], nouns: ['viento', 'aire'], synonyms: ['brisa', 'vendaval'], antonyms: ['calma'] },
    { id: 'nieve', category: 'Clima', variations: [{ text: 'Nieve', icon: 'mdi:weather-snowy' }], nouns: ['nieve', 'nevada'], synonyms: ['nevada'], antonyms: [] },

    // Fringe: Colores
    { id: 'rojo', category: 'Colores', variations: [{ text: 'Rojo', icon: 'mdi:circle', style: { color: 'red' } }], nouns: ['rojo', 'color'], synonyms: ['carmesí', 'escarlata'], antonyms: [] },
    { id: 'azul', category: 'Colores', variations: [{ text: 'Azul', icon: 'mdi:circle', style: { color: 'blue' } }], nouns: ['azul', 'color'], synonyms: ['añil', 'turquesa'], antonyms: [] },
    { id: 'amarillo', category: 'Colores', variations: [{ text: 'Amarillo', icon: 'mdi:circle', style: { color: 'yellow' } }], nouns: ['amarillo', 'color'], synonyms: ['dorado'], antonyms: [] },
    { id: 'verde', category: 'Colores', variations: [{ text: 'Verde', icon: 'mdi:circle', style: { color: 'green' } }], nouns: ['verde', 'color'], synonyms: ['esmeralda'], antonyms: [] },
    { id: 'naranja_color', category: 'Colores', variations: [{ text: 'Naranja', icon: 'mdi:circle', style: { color: 'orange' } }], nouns: ['naranja', 'color'], synonyms: ['anaranjado'], antonyms: [] },
    { id: 'morado', category: 'Colores', variations: [{ text: 'Morado', icon: 'mdi:circle', style: { color: 'purple' } }], nouns: ['morado', 'púrpura', 'color'], synonyms: ['púrpura', 'violeta'], antonyms: [] },
    { id: 'rosado', category: 'Colores', variations: [{ text: 'Rosado', icon: 'mdi:circle', style: { color: 'pink' } }], nouns: ['rosado', 'rosa', 'color'], synonyms: ['rosa'], antonyms: [] },
    { id: 'negro', category: 'Colores', variations: [{ text: 'Negro', icon: 'mdi:circle', style: { color: 'black' } }], nouns: ['negro', 'oscuridad', 'color'], synonyms: ['oscuro'], antonyms: ['blanco'] },
    { id: 'blanco', category: 'Colores', variations: [{ text: 'Blanco', icon: 'mdi:circle-outline', style: { color: 'black' } }], nouns: ['blanco', 'claridad', 'color'], synonyms: ['claro', 'albo'], antonyms: ['negro'] },
    { id: 'gris', category: 'Colores', variations: [{ text: 'Gris', icon: 'mdi:circle-half-full', style: { color: 'gray' } }], nouns: ['gris', 'color'], synonyms: [], antonyms: [] },
    { id: 'marron', category: 'Colores', variations: [{ text: 'Marrón', icon: 'mdi:square', style: { color: 'brown' } }], nouns: ['marrón', 'castaño', 'color'], synonyms: ['castaño', 'pardo'], antonyms: [] },

    // Fringe: Números
    { id: 'uno', category: 'Números', variations: [{ text: 'Uno', icon: 'mdi:numeric-1-circle' }], nouns: ['uno', 'número'], synonyms: [], antonyms: [] },
    { id: 'dos', category: 'Números', variations: [{ text: 'Dos', icon: 'mdi:numeric-2-circle' }], nouns: ['dos', 'número'], synonyms: [], antonyms: [] },
    { id: 'tres', category: 'Números', variations: [{ text: 'Tres', icon: 'mdi:numeric-3-circle' }], nouns: ['tres', 'número'], synonyms: [], antonyms: [] },
    { id: 'cuatro', category: 'Números', variations: [{ text: 'Cuatro', icon: 'mdi:numeric-4-circle' }], nouns: ['cuatro', 'número'], synonyms: [], antonyms: [] },
    { id: 'cinco', category: 'Números', variations: [{ text: 'Cinco', icon: 'mdi:numeric-5-circle' }], nouns: ['cinco', 'número'], synonyms: [], antonyms: [] },
    { id: 'seis', category: 'Números', variations: [{ text: 'Seis', icon: 'mdi:numeric-6-circle' }], nouns: ['seis', 'número'], synonyms: [], antonyms: [] },
    { id: 'siete', category: 'Números', variations: [{ text: 'Siete', icon: 'mdi:numeric-7-circle' }], nouns: ['siete', 'número'], synonyms: [], antonyms: [] },
    { id: 'ocho', category: 'Números', variations: [{ text: 'Ocho', icon: 'mdi:numeric-8-circle' }], nouns: ['ocho', 'número'], synonyms: [], antonyms: [] },
    { id: 'nueve', category: 'Números', variations: [{ text: 'Nueve', icon: 'mdi:numeric-9-circle' }], nouns: ['nueve', 'número'], synonyms: [], antonyms: [] },
    { id: 'diez', category: 'Números', variations: [{ text: 'Diez', icon: 'mdi:numeric-10-circle' }], nouns: ['diez', 'número'], synonyms: [], antonyms: [] },
];
